export const BUSINESS_NAME = 'F.A.S. Motorsports';
export const BUSINESS_EMAIL = 'sales@fasmotorsports.com';

export const BUSINESS_PHONE_E164 = '+18122009012';
export const BUSINESS_PHONE_NATIONAL = '(812) 200-9012';
export const BUSINESS_PHONE_INTL_DISPLAY = '+1 (812) 200-9012';

export const BUSINESS_ADDRESS_LINE1 = '6161 Riverside Dr';
export const BUSINESS_ADDRESS_LOCALITY = 'Punta Gorda';
export const BUSINESS_ADDRESS_REGION = 'FL';
export const BUSINESS_ADDRESS_POSTAL_CODE = '33982';
export const BUSINESS_ADDRESS_COUNTRY = 'US';
export const BUSINESS_ADDRESS_DISPLAY = `${BUSINESS_ADDRESS_LINE1}, ${BUSINESS_ADDRESS_LOCALITY}, ${BUSINESS_ADDRESS_REGION} ${BUSINESS_ADDRESS_POSTAL_CODE}`;
