nodeLinker: node-modules

packageExtensions:
  "@netlify/ai@*":
    dependencies:
      "@netlify/mcp": "npm:^1.13.0"
  "@netlify/build@*":
    dependencies:
      "@types/node": "*"
  "@netlify/edge-functions-dev@*":
    dependencies:
      "@netlify/edge-functions": "npm:2.18.2"
  "@portabletext/editor@*":
    peerDependencies:
      react-dom: "*"
  "@sanity/cli@*":
    dependencies:
      react: 18.3.1
  "@sanity/insert-menu@*":
    dependencies:
      styled-components: "*"
  "@sanity/migrate@*":
    dependencies:
      "@types/react": "*"
  "@sanity/mutator@*":
    dependencies:
      "@types/react": "*"
  "@sanity/schema@*":
    dependencies:
      "@types/react": "*"
  "@sanity/sdk@*":
    dependencies:
      "@types/react": "*"
  "@sanity/util@*":
    dependencies:
      "@types/react": "*"
  "@types/next@*":
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1
  cssstyle@*:
    dependencies:
      postcss: "*"
  media-chrome@*:
    dependencies:
      react: 18.3.1
  resend@*:
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1

yarnPath: .yarn/releases/yarn-4.12.0.cjs
