yarnPath: .yarn/releases/yarn-4.5.3.cjs
nodeLinker: node-modules

packageExtensions:
  '@portabletext/editor@*':
    peerDependencies:
      react-dom: '*'
  '@netlify/build@*':
    dependencies:
      '@types/node': '*'
  '@sanity/cli@*':
    dependencies:
      react: '18.3.1'
  '@sanity/insert-menu@*':
    dependencies:
      styled-components: '*'
  '@sanity/migrate@*':
    dependencies:
      '@types/react': '*'
  '@sanity/mutator@*':
    dependencies:
      '@types/react': '*'
  '@sanity/schema@*':
    dependencies:
      '@types/react': '*'
  '@sanity/sdk@*':
    dependencies:
      '@types/react': '*'
  '@sanity/util@*':
    dependencies:
      '@types/react': '*'
  '@types/next@*':
    dependencies:
      react: '18.3.1'
      react-dom: '18.3.1'
  'cssstyle@*':
    dependencies:
      postcss: '*'
  'astro@*':
    peerDependencies:
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  'media-chrome@*':
    dependencies:
      react: '18.3.1'
  'resend@*':
    dependencies:
      react: '18.3.1'
      react-dom: '18.3.1'
