yarnPath: .yarn/releases/yarn-3.6.4.cjs
nodeLinker: node-modules

packageExtensions:
  '@portabletext/editor@*':
    peerDependencies:
      react-dom: '*'
  '@sanity/telemetry@*':
    peerDependencies:
      react: '*'
    peerDependenciesMeta:
      react:
        optional: true
