[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200

[build]
  command = "yarn install --immutable && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.20"
  NETLIFY_USE_YARN = "true"
  NETLIFY_EXPERIMENTAL_YARN_BERRY = "true"
  YARN_VERSION = "3.6.4"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Help Netlify Dev/Visual Editor choose the right framework command
[dev]
  framework = "astro"
  command = "astro dev --host 0.0.0.0 --port 3000"
  targetPort = 3000
  port = 8888
  autoLaunch = false

# Build plugins
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      ".astro",
      ".cache",
      "package-lock.json"
    ]

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
    extract = true

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-a11y"
  [plugins.inputs]
    checkPaths = ["/"]
    failOnError = false
    ignore = ["/admin/*", "/studio/*"]

[[plugins]]
  package = "@netlify/plugin-compress"

[[plugins]]
  package = "netlify-plugin-csp"
  [plugins.inputs]
    reportOnly = false
  [plugins.inputs.policy]
    defaultSrc = ["'self'"]
    scriptSrc  = ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://www.google.com/recaptcha/", "https://www.gstatic.com/recaptcha/", "https://cdn.auth0.com", "https://js.stripe.com"]
    connectSrc = ["'self'", "https://*.sanity.io", "https://api.stripe.com", "https://*.shipengine.com", "https://cdn.auth0.com", "https://login.fasmotorsports.com"]
    imgSrc     = ["'self'", "data:", "blob:", "https:"]
    styleSrc   = ["'self'", "'unsafe-inline'"]
    fontSrc    = ["'self'", "data:", "https:"]
    frameSrc   = ["https://www.google.com/recaptcha/", "https://js.stripe.com", "https://*.auth0.com", "https://login.fasmotorsports.com"]

# Caching headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
