[build]
  command = "yarn run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.20"
  PUBLIC_SANITY_PROJECT_ID = "r4og35qd"
  PUBLIC_SANITY_API_TOKEN = "skCMm9GRjvBWktDQzjbFs7sezCvM8fndJM9CHzr7F9YEbFnbdi1NalTDl9Py5io4RguSICf076vy5y32StIohWVCnmuJ7kYztnqOxCKD2OXx7LNRPwHbIAFX0aEMqNd0fmOhfx186VbsapvVuWsMpvvkmMnlmuYho1rkJoalKSQ7ZfxHYCPK"
  NETLIFY_USE_YARN = "true"
  NETLIFY_EXPERIMENTAL_YARN_BERRY = "true"
  YARN_VERSION = "4.9.1"