[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

## Note: Custom auth uses Astro API under /api/auth/*; no redirects needed.

[build]
  command = "yarn install && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.20"
  PHP_VERSION = "8.3"
  NETLIFY_USE_YARN = "true"
  NETLIFY_EXPERIMENTAL_YARN_BERRY = "true"
  YARN_VERSION = "3.6.4"
  # Used by /api/checkout to build absolute success/cancel URLs
  # In production on Netlify, forwarded host headers are present, so this is a safe default.
  PUBLIC_BASE_URL = "https://fasmotorsports.com"
  # Canonical site URL used as a fallback by auth flows
  PUBLIC_SITE_URL = "https://www.fasmotorsports.com"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Help Netlify Dev choose the right framework command
[dev]
  framework = "astro"
  command = "astro dev --host 0.0.0.0 --port 3000"
  targetPort = 3000
  port = 8888
  autoLaunch = false

# Build plugins
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      ".astro",
      ".cache",
      "package-lock.json"
    ]

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
    extract = true

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://www.fasmotorsports.com"
    sitemapPath = "/sitemap_index.xml"


# (moved to deploy-preview context to save prod build time)


# Run a11y checks only on Deploy Previews to avoid slowing/failing production builds
[context.deploy-preview]
  # Run Lighthouse only on Deploy Previews
  [[plugins]]
    package = "@netlify/plugin-lighthouse"

  # Run link checking only on Deploy Previews to avoid flakiness/crashes
  [[plugins]]
    package = "netlify-plugin-checklinks"

## Removed netlify-plugin-csp (not on npm) in favor of static CSP header below

# Caching headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://js.stripe.com https://app.netlify.com https://ve.netlify.app https://*.netlify.app; connect-src 'self' https://*.sanity.io https://api.stripe.com https://*.shipengine.com https://app.netlify.com https://ve.netlify.app https://*.netlify.app wss://*.netlify.app wss://ve.netlify.app; img-src 'self' data: blob: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data: https:; media-src https: blob:; frame-src https://www.google.com/recaptcha/ https://js.stripe.com https://app.netlify.com https://*.netlify.app https://www.youtube.com https://youtube.com; frame-ancestors 'self' https://app.netlify.com https://*.netlify.app"
# Avoid caching the account page so auth callback always runs with fresh HTML
[[headers]]
  for = "/account"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/account/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
