[build]
  command = "yarn install --ignore-optional && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.20"
  NETLIFY_USE_YARN = "true"
  NETLIFY_EXPERIMENTAL_YARN_BERRY = "true"
  YARN_VERSION = "3.6.4"