[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200

[build]
  command = "yarn install --immutable && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  GO_VERSION = "1.20"
  NETLIFY_USE_YARN = "true"
  NETLIFY_EXPERIMENTAL_YARN_BERRY = "true"
  YARN_VERSION = "3.6.4"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Help Netlify Dev/Visual Editor choose the right framework command
[dev]
  framework = "astro"
  command = "yarn dev"
  targetPort = 3000
  port = 8888
  autoLaunch = false
