// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 21a79c897ec6fdec "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' | 'btn - glow off' // Variant
 * link?: string // Link
 * title?: string // Title
 * icon?: undefined // Icon
 * newTab?: boolean // New Tab
}} Props

 */
import { stdin_default } from "./chunks/chunk-TQTC2MK6.js";
import "./chunks/chunk-4NPMLM6U.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:main-button
import { Fragment } from "react";
import { ContextProviders } from "unframer";
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "chiubjAu6",
	xl: "u8HXU5hd9",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<FramerContextProviders
			routes={routes}
			framerSiteId={
				"21a79c897ec6fdecc33a23f68d80f3e3f699d3e22efca4618d9f9fe12404d644"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</FramerContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<FramerContextProviders
			routes={routes}
			framerSiteId={
				"21a79c897ec6fdecc33a23f68d80f3e3f699d3e22efca4618d9f9fe12404d644"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</FramerContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var main_button_default = ComponentWithRoot;
export { main_button_default as default };
