// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 21a79c897ec6fdec "landio (copy)", do not edit manually */
('use client');

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import '@/lib/polyfillReactDomResourceApi';
import '@/components/framer/styles.css';
import './cta-section.css';

import { stdin_default as stdin_default6 } from './chunks/chunk-FAVUELWT.js';
import './chunks/chunk-WL2IUHJ5.js';
import { stdin_default as stdin_default5 } from './chunks/chunk-AAKOUMSY.js';
import {
  stdin_default as stdin_default2,
  stdin_default2 as stdin_default3,
  stdin_default3 as stdin_default4,
} from './chunks/chunk-DJT75QUV.js';
import { stdin_default } from './chunks/chunk-4NPMLM6U.js';
import { className, css, fonts } from './chunks/chunk-XU5APAQZ.js';
import { routes } from './chunks/chunk-YOD5Q24P.js';

// virtual:cta-section
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';

// /:https://framerusercontent.com/modules/5WvDX1GZFDvBXvm0ujJR/YDJFMIGXC9XlgL5CeURv/kDloua7zU.js
import { jsx as _jsx2, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
import { useRef } from 'react';

var MotionDivWithFX = withFX(motion.div);
var RichTextWithFX = withFX(RichText);
var MainButtonFonts = getFonts(stdin_default6);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var ElementsSocialMediaFonts = getFonts(stdin_default4);
var cycleOrder = ['ec8cBy25t', 'VNkgiDYTT', 'JPu3JhM8D'];
var serializationHash = 'framer-XPJ2H';
var variantClassNames = {
  ec8cBy25t: 'framer-v-1xtnd9z',
  JPu3JhM8D: 'framer-v-1dz9b0w',
  VNkgiDYTT: 'framer-v-11vtk6b',
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: 'spring',
};
var animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 60,
};
var transition2 = {
  damping: 60,
  delay: 0.3,
  mass: 1,
  stiffness: 320,
  type: 'spring',
};
var transition3 = {
  damping: 60,
  delay: 0.4,
  mass: 1,
  stiffness: 320,
  type: 'spring',
};
var transition4 = {
  damping: 60,
  delay: 0.5,
  mass: 1,
  stiffness: 320,
  type: 'spring',
};
var transition5 = {
  damping: 60,
  delay: 0.6,
  mass: 1,
  stiffness: 320,
  type: 'spring',
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
  Desktop: 'ec8cBy25t',
  Phone: 'JPu3JhM8D',
  Tablet: 'VNkgiDYTT',
};
var getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? 'ec8cBy25t',
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className: className2,
    layoutId,
    variant,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'ec8cBy25t',
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.section
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              'framer-1xtnd9z',
              'cta-section',
              className2,
              classNames,
            )}
            data-framer-name={'Desktop'}
            layoutDependency={layoutDependency}
            layoutId={'ec8cBy25t'}
            ref={refBinding}
            style={{
              backgroundColor:
                'var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0))',
              width: '100%',
              margin: 0,
              position: 'relative',
              ...style,
            }}
            {...addPropertyOverrides(
              {
                JPu3JhM8D: {
                  'data-framer-name': 'Phone',
                },
                VNkgiDYTT: {
                  'data-framer-name': 'Tablet',
                },
              },
              baseVariant,
              gestureVariant,
            )}
          >
            <video
              autoPlay
              loop
              muted
              playsInline
              src="https://framerusercontent.com/assets/1g8IkhtJmlWcC4zEYWKUmeGWzI.mp4"
              style={{
                position: 'absolute',
                inset: 0,
                width: '100%',
                height: '100%',
                objectFit: 'cover',
                pointerEvents: 'none',
                zIndex: 0,
                filter: 'grayscale(100%) contrast(1.1) brightness(0.7)',
              }}
            />
            <div
              style={{
                position: 'absolute',
                inset: 3,
                backgroundImage: 'url()',
                backgroundSize: 'contain',
                backgroundPosition: 'center',
                opacity: '100%',
                width: '100%',
                mixBlendMode: 'screen',
                pointerEvents: 'none',
                zIndex: 1,
                filter: 'grayscale(10%) contrast(1)',
                backgroundRepeat: 'no-repeat',
              }}
            />
            <motion.div
              className={'framer-6vqytm cta-section__inner'}
              data-framer-name={'container'}
              layoutDependency={layoutDependency}
              layoutId={'VhD5uACqY'}
            >
              <motion.div
                className={'framer-mdsrkf'}
                data-framer-name={'text'}
                layoutDependency={layoutDependency}
                layoutId={'igWqpDr5C'}
              >
                <MotionDivWithFX
                  __framer__animate={{ transition: transition2 }}
                  __framer__animateOnce={true}
                  __framer__enter={animation}
                  __framer__styleAppearEffectEnabled={true}
                  __framer__threshold={0}
                  __perspectiveFX={false}
                  __smartComponentFX={true}
                  __targetOpacity={1}
                  className={'framer-mn7w53 cta-section__tag'}
                  data-framer-name={'tag'}
                  layoutDependency={layoutDependency}
                  layoutId={'ENMiMNt7g'}
                >
                  <span className={'cta-section__tag-line w-full'} />
                  <span className={'font-borg uppercase tracking-tight w-full'}>
                    <span className="font-borg text-4xl text-primaryB">
                      F.a.S.{' '}
                    </span>
                    <span className="font-ethno">Motorsports</span>
                  </span>
                  <span className={'cta-section__tag-line'} />
                </MotionDivWithFX>
                <MotionDivWithFX
                  __framer__animate={{ transition: transition3 }}
                  __framer__animateOnce={true}
                  __framer__enter={animation}
                  __framer__styleAppearEffectEnabled={true}
                  __framer__threshold={0}
                  __perspectiveFX={false}
                  __smartComponentFX={true}
                  __targetOpacity={1}
                  className={'cta-section__heading text-center'}
                  data-framer-name={'primary heading'}
                  layoutDependency={layoutDependency}
                  layoutId={'sB7t50ewJ'}
                >
                  <motion.h2
                    className={
                      'font-ethno text-accent uppercase tracking-[0.08em] leading-tight text-center'
                    }
                  >
                    Power Up Your Ride! Let’s{' '}
                    <span
                      className={
                        'font-ethno italic normal-case tracking-normal'
                      }
                    >
                      Build Together
                    </span>
                  </motion.h2>
                </MotionDivWithFX>
                <MotionDivWithFX
                  __framer__animate={{ transition: transition4 }}
                  __framer__animateOnce={true}
                  __framer__enter={animation}
                  __framer__styleAppearEffectEnabled={true}
                  __framer__threshold={0}
                  __perspectiveFX={false}
                  __smartComponentFX={true}
                  __targetOpacity={1}
                  className={'cta-section__lede'}
                  data-framer-name={'lede'}
                  layoutDependency={layoutDependency}
                  layoutId={'OPs0xtkkj'}
                >
                  <motion.p
                    className={
                      'font-captain tracking-widest text-3xl text-white/60 text-outline outline-white uppercase text-center'
                    }
                  >
                    Premium performance upgrades tailored to your build.
                  </motion.p>
                </MotionDivWithFX>
              </motion.div>
              <ComponentViewportProvider
                height={50}
                y={
                  (componentViewport?.y || 0) +
                  100 +
                  (((componentViewport?.height || 200) - 200 - 528.4) / 2 +
                    0 +
                    0) +
                  0 +
                  262.4
                }
                {...addPropertyOverrides(
                  {
                    JPu3JhM8D: {
                      y:
                        (componentViewport?.y || 0) +
                        80 +
                        (((componentViewport?.height || 572) - 160 - 514) / 2 +
                          0 +
                          0) +
                        0 +
                        248,
                    },
                    VNkgiDYTT: {
                      y:
                        (componentViewport?.y || 0) +
                        100 +
                        (((componentViewport?.height || 578) - 200 - 528.4) /
                          2 +
                          0 +
                          0) +
                        0 +
                        262.4,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                )}
              >
                <SmartComponentScopedContainerWithFX
                  __framer__animate={{
                    transition: transition4,
                  }}
                  __framer__animateOnce={true}
                  __framer__enter={animation}
                  __framer__styleAppearEffectEnabled={true}
                  __framer__threshold={0}
                  __perspectiveFX={false}
                  __smartComponentFX={true}
                  __targetOpacity={1}
                  className={'framer-bmyti8-container'}
                  layoutDependency={layoutDependency}
                  layoutId={'TXod1qeVd-container'}
                  nodeId={'TXod1qeVd'}
                  rendersWithMotion={true}
                  scopeId={'kDloua7zU'}
                >
                  {_jsx2(stdin_default6, {
                    D_lQwlRhv: stdin_default5,
                    height: '100%',
                    id: 'TXod1qeVd',
                    layoutId: 'TXod1qeVd',
                    pkd7Pcy3s: true,
                    variant: 'u8HXU5hd9',
                    width: '100%',
                    WygjbYACO: 'Shop Products',
                    ypOX2jdFN: '/shop',
                    ...addPropertyOverrides(
                      {
                        JPu3JhM8D: {
                          variant: 'chiubjAu6',
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  })}
                </SmartComponentScopedContainerWithFX>
              </ComponentViewportProvider>
              <MotionDivWithFX
                __framer__animate={{
                  transition: transition5,
                }}
                __framer__animateOnce={true}
                __framer__enter={animation}
                __framer__styleAppearEffectEnabled={true}
                __framer__threshold={0}
                __perspectiveFX={false}
                __smartComponentFX={true}
                __targetOpacity={1}
                className={'framer-1dm4u5y cta-section__actions'}
                data-framer-name={'social links'}
                layoutDependency={layoutDependency}
                layoutId={'uBXpNmxVU'}
              >
                <ComponentViewportProvider
                  height={40}
                  y={
                    (componentViewport?.y || 0) +
                    100 +
                    (((componentViewport?.height || 200) - 200 - 528.4) / 2 +
                      0 +
                      0) +
                    0 +
                    336.4 +
                    0
                  }
                  {...addPropertyOverrides(
                    {
                      JPu3JhM8D: {
                        y:
                          (componentViewport?.y || 0) +
                          80 +
                          (((componentViewport?.height || 572) - 160 - 514) /
                            2 +
                            0 +
                            0) +
                          0 +
                          322 +
                          0,
                      },
                      VNkgiDYTT: {
                        y:
                          (componentViewport?.y || 0) +
                          100 +
                          (((componentViewport?.height || 578) - 200 - 528.4) /
                            2 +
                            0 +
                            0) +
                          0 +
                          336.4 +
                          0,
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  )}
                >
                  <SmartComponentScopedContainer
                    className={'framer-1j926yj-container'}
                    layoutDependency={layoutDependency}
                    layoutId={'hiRG70yf5-container'}
                    nodeId={'hiRG70yf5'}
                    rendersWithMotion={true}
                    scopeId={'kDloua7zU'}
                  >
                    {_jsx2(stdin_default4, {
                      height: '100%',
                      id: 'hiRG70yf5',
                      layoutId: 'hiRG70yf5',
                      RhBoiefR8: stdin_default,
                      width: '100%',
                      YdTA2k7Lp: 'https://x.com/home',
                    })}
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
                <motion.div
                  className={'framer-saktx7'}
                  data-framer-name={'separation'}
                  layoutDependency={layoutDependency}
                  layoutId={'BimQpy49a'}
                  style={{
                    backgroundColor:
                      'var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(255, 255, 255, 0.07))',
                  }}
                />
                <ComponentViewportProvider
                  height={40}
                  y={
                    (componentViewport?.y || 0) +
                    100 +
                    (((componentViewport?.height || 200) - 200 - 528.4) / 2 +
                      0 +
                      0) +
                    0 +
                    336.4 +
                    0
                  }
                  {...addPropertyOverrides(
                    {
                      JPu3JhM8D: {
                        y:
                          (componentViewport?.y || 0) +
                          80 +
                          (((componentViewport?.height || 572) - 160 - 514) /
                            2 +
                            0 +
                            0) +
                          0 +
                          322 +
                          0,
                      },
                      VNkgiDYTT: {
                        y:
                          (componentViewport?.y || 0) +
                          100 +
                          (((componentViewport?.height || 578) - 200 - 528.4) /
                            2 +
                            0 +
                            0) +
                          0 +
                          336.4 +
                          0,
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  )}
                >
                  <SmartComponentScopedContainer
                    className={'framer-xhz6ho-container'}
                    layoutDependency={layoutDependency}
                    layoutId={'U42syeobH-container'}
                    nodeId={'U42syeobH'}
                    rendersWithMotion={true}
                    scopeId={'kDloua7zU'}
                  >
                    {_jsx2(stdin_default4, {
                      height: '100%',
                      id: 'U42syeobH',
                      layoutId: 'U42syeobH',
                      RhBoiefR8: stdin_default2,
                      width: '100%',
                      YdTA2k7Lp: 'https://www.instagram.com/',
                    })}
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
                <motion.div
                  className={'framer-a8tg8v'}
                  data-framer-name={'separation'}
                  layoutDependency={layoutDependency}
                  layoutId={'Jgyr1VdRq'}
                  style={{
                    backgroundColor:
                      'var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(255, 255, 255, 0.07))',
                  }}
                />
                <ComponentViewportProvider
                  height={40}
                  y={
                    (componentViewport?.y || 0) +
                    100 +
                    (((componentViewport?.height || 200) - 200 - 528.4) / 2 +
                      0 +
                      0) +
                    0 +
                    336.4 +
                    0
                  }
                  {...addPropertyOverrides(
                    {
                      JPu3JhM8D: {
                        y:
                          (componentViewport?.y || 0) +
                          80 +
                          (((componentViewport?.height || 572) - 160 - 514) /
                            2 +
                            0 +
                            0) +
                          0 +
                          322 +
                          0,
                      },
                      VNkgiDYTT: {
                        y:
                          (componentViewport?.y || 0) +
                          100 +
                          (((componentViewport?.height || 578) - 200 - 528.4) /
                            2 +
                            0 +
                            0) +
                          0 +
                          336.4 +
                          0,
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  )}
                >
                  <SmartComponentScopedContainer
                    className={'framer-1mar2n1-container'}
                    layoutDependency={layoutDependency}
                    layoutId={'losRqOOKa-container'}
                    nodeId={'losRqOOKa'}
                    rendersWithMotion={true}
                    scopeId={'kDloua7zU'}
                  >
                    {_jsx2(stdin_default4, {
                      height: '100%',
                      id: 'losRqOOKa',
                      layoutId: 'losRqOOKa',
                      RhBoiefR8: stdin_default3,
                      width: '100%',
                      YdTA2k7Lp: 'https://www.facebook.com/',
                    })}
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </MotionDivWithFX>
              <RichTextWithFX
                __framer__animate={{
                  transition: transition5,
                }}
                __framer__animateOnce={true}
                __framer__enter={animation}
                __framer__styleAppearEffectEnabled={true}
                __framer__threshold={0}
                __fromCanvasComponent={true}
                __perspectiveFX={false}
                __smartComponentFX={true}
                __targetOpacity={1}
                className={'framer-19oal4v cta-section__metrics'}
                fonts={['Ethno', 'Cyber', 'Mono']}
                layoutDependency={layoutDependency}
                layoutId={'rfZJYBGkZ'}
                verticalAlignment={'top'}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.p
                    className={'framer-styles-preset-1kvyxmc'}
                    data-styles-preset={'n7RLEGRKm'}
                    style={{
                      '--framer-text-alignment': 'center',
                    }}
                  >
                    {'fasmotorsports.com'}
                  </motion.p>
                </React.Fragment>
              </RichTextWithFX>
            </motion.div>
            <video
              autoPlay
              loop
              muted
              playsInline
              src="https://framerusercontent.com/assets/1g8IkhtJmlWcC4zEYWKUmeGWzI.mp4"
              style={{
                position: 'absolute',
                inset: 0,
                width: '100%',
                height: '100%',
                objectFit: 'cover',
                pointerEvents: 'none',
                zIndex: 0,
                filter: 'grayscale(100%) contrast(1.1) brightness(0.1)',
              }}
            />
            <motion.div
              className={'framer-2gp519'}
              data-framer-name={'border'}
              layoutDependency={layoutDependency}
              layoutId={'Wf4PPDqW3'}
              style={{
                background:
                  'radial-gradient(50% 50% at 50% 50%, var(--background), rgba(255, 255, 255, 0.07)) 0%, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0)) 100%)',
              }}
            />
            <video
              autoPlay
              loop
              muted
              playsInline
              src="https://framerusercontent.com/assets/1g8IkhtJmlWcC4zEYWKUmeGWzI.mp4"
              style={{
                position: 'absolute',
                inset: 0,
                width: '100%',
                height: '100%',
                objectFit: 'cover',
                pointerEvents: 'none',
                zIndex: 0,
                filter: 'grayscale(100%) contrast(1.1) brightness(0.2)',
              }}
            />
            <motion.div
              className={'framer-1jnyfdf'}
              data-framer-name={'bg shape'}
              layoutDependency={layoutDependency}
              layoutId={'leKLWtH8k'}
              style={{
                background:
                  'radial-gradient(50% 50% at 50% 50%, var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7)) 0%, rgba(4, 7, 13, 0) 100%)',
                borderBottomLeftRadius: 10,
                borderBottomRightRadius: 10,
                borderTopLeftRadius: 10,
                borderTopRightRadius: 10,
                opacity: 0.1,
                rotate: -13,
              }}
            />
            <ComponentViewportProvider>
              <SmartComponentScopedContainer
                className={'framer-17j4hvp-container'}
                isAuthoredByUser={true}
                isModuleExternal={true}
                layoutDependency={layoutDependency}
                layoutId={'tZSJKG6DP-container'}
                nodeId={'tZSJKG6DP'}
                rendersWithMotion={true}
                scopeId={'kDloua7zU'}
                style={{
                  mask: 'radial-gradient(40% 46% at 50.9% 89.5%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0.8) 36.8823902027027%, rgba(0, 0, 0, 0) 100%) add',
                  WebkitMask:
                    'radial-gradient(40% 46% at 50.9% 89.5%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0.8) 36.8823902027027%, rgba(0, 0, 0, 0) 100%) add',
                }}
              ></SmartComponentScopedContainer>
            </ComponentViewportProvider>
          </motion.section>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css2 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-XPJ2H.framer-12mf41w, .framer-XPJ2H .framer-12mf41w { display: block; }',
  '.framer-XPJ2H.framer-1xtnd9z { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 40px 100px 40px; position: relative; width: 1280px; }',
  '.framer-XPJ2H .framer-6vqytm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1240px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 3; }',
  '.framer-XPJ2H .framer-mdsrkf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; max-width: 613px; overflow: visible; padding: 0px; position: relative; width: 100%; }',
  '.framer-XPJ2H .framer-mn7w53 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 24px 0px 24px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: 1; }',
  '.framer-XPJ2H .framer-itlxvr, .framer-XPJ2H .framer-14gcsf2 { flex: none; height: 1px; overflow: hidden; position: relative; width: 69px; }',
  '.framer-XPJ2H .framer-xel6ch { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-XPJ2H .framer-yua25m, .framer-XPJ2H .framer-19oal4v { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-XPJ2H .framer-v306pb { flex: none; height: auto; max-width: 75%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-XPJ2H .framer-bmyti8-container, .framer-XPJ2H .framer-1j926yj-container, .framer-XPJ2H .framer-xhz6ho-container, .framer-XPJ2H .framer-1mar2n1-container { flex: none; height: auto; position: relative; width: auto; }',
  '.framer-XPJ2H .framer-1dm4u5y { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-XPJ2H .framer-saktx7, .framer-XPJ2H .framer-a8tg8v { flex: none; height: 24px; overflow: hidden; position: relative; width: 2px; }',
  '.framer-XPJ2H .framer-2gp519 { bottom: 0px; flex: none; height: 4px; left: 0px; position: absolute; right: 0px; z-index: 1; }',
  '.framer-XPJ2H .framer-1jnyfdf { bottom: -249px; flex: none; height: 499px; left: calc(50.00000000000002% - 793px / 2); pointer-events: none; position: absolute; width: 793px; z-index: 4; }',
  '.framer-XPJ2H .framer-17j4hvp-container { bottom: 0px; flex: none; height: 642px; left: 0px; pointer-events: none; position: absolute; right: 0px; z-index: 3; }',
  '.framer-XPJ2H.framer-v-11vtk6b.framer-1xtnd9z { width: 810px; }',
  '.framer-XPJ2H.framer-v-1dz9b0w.framer-1xtnd9z { padding: 80px 18px 80px 18px; width: 390px; }',
  '.framer-XPJ2H.framer-v-1dz9b0w .framer-1jnyfdf { height: 378px; left: calc(50.00000000000002% - 600px / 2); width: 600px; }',
  ...css,
];
var FramerkDloua7zU = withCSS(Component, css2, 'framer-XPJ2H');
var stdin_default7 = FramerkDloua7zU;
FramerkDloua7zU.displayName = 'CTA section';
FramerkDloua7zU.defaultProps = {
  height: 578,
  width: 1280,
};
addPropertyControls2(FramerkDloua7zU, {
  variant: {
    options: ['ec8cBy25t', 'VNkgiDYTT', 'JPu3JhM8D'],
    optionTitles: ['Desktop', 'Tablet', 'Phone'],
    title: 'Variant',
    type: ControlType2.Enum,
  },
});
addFonts(
  FramerkDloua7zU,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'italic',
          unicodeRange:
            'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'italic',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'italic',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'italic',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'italic',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'italic',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'italic',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2',
          weight: '500',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2',
          weight: '500',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2',
          weight: '500',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2',
          weight: '500',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2',
          weight: '500',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2',
          weight: '500',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2',
          weight: '500',
        },
        {
          family: 'Instrument Serif',
          source: 'google',
          style: 'italic',
          url: 'https://fonts.gstatic.com/s/instrumentserif/v4/jizHRFtNs2ka5fXjeivQ4LroWlx-6zATjnTNgNq55w.woff2',
          weight: '400',
        },
      ],
    },
    ...MainButtonFonts,
    ...ElementsSocialMediaFonts,
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  },
);

// virtual:cta-section
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {
  base: 'JPu3JhM8D',
  md: 'VNkgiDYTT',
  xl: 'ec8cBy25t',
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        '21a79c897ec6fdecc33a23f68d80f3e3f699d3e22efca4618d9f9fe12404d644'
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default7, {
        ...rest,
      })}
    </ContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        '21a79c897ec6fdecc33a23f68d80f3e3f699d3e22efca4618d9f9fe12404d644'
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default7}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default7);
var cta_section_default = ComponentWithRoot;
export { cta_section_default as default };
