// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'View Project' // Variant
}} Props

 */
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:cursor
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/L1QNjNU6yuYnIimpJdsc/fI1vp7nvLv6WCFSwQCSU/TcjhCmN5c.js
import { jsx as _jsx } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
var cycleOrder = ['N4TdUsQKx', 'D8CGcjC8G'];
var serializationHash = 'framer-Rec7f';
var variantClassNames = {
  D8CGcjC8G: 'framer-v-17zs766',
  N4TdUsQKx: 'framer-v-1lik2pt'
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: 'spring'
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
  'View Project': 'D8CGcjC8G',
  Default: 'N4TdUsQKx'
};
var getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'N4TdUsQKx'
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'N4TdUsQKx',
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const isDisplayed = () => {
    if (baseVariant === 'D8CGcjC8G') return true;
    return false;
  };
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(scopingClassNames, 'framer-1lik2pt', className, classNames)}
            data-framer-name={'Default'}
            layoutDependency={layoutDependency}
            layoutId={'N4TdUsQKx'}
            ref={ref ?? ref1}
            style={{
              '--border-bottom-width': '0px',
              '--border-color': 'rgba(0, 0, 0, 0)',
              '--border-left-width': '0px',
              '--border-right-width': '0px',
              '--border-style': 'solid',
              '--border-top-width': '0px',
              backdropFilter: 'none',
              backgroundColor: 'rgb(230, 230, 230)',
              borderBottomLeftRadius: 40,
              borderBottomRightRadius: 40,
              borderTopLeftRadius: 40,
              borderTopRightRadius: 40,
              boxShadow: '0px 0px 20px 4px rgba(196, 196, 196, 0.3)',
              WebkitBackdropFilter: 'none',
              ...style
            }}
            variants={{
              D8CGcjC8G: {
                '--border-bottom-width': '1px',
                '--border-color': 'rgb(214, 214, 214)',
                '--border-left-width': '1px',
                '--border-right-width': '1px',
                '--border-style': 'solid',
                '--border-top-width': '1px',
                backdropFilter: 'blur(6px)',
                backgroundColor: 'rgba(99, 99, 99, 0.3)',
                boxShadow: '0px 0px 20px 4px rgba(92, 92, 92, 0.3)',
                WebkitBackdropFilter: 'blur(6px)'
              }
            }}
            {...addPropertyOverrides(
              {
                D8CGcjC8G: {
                  'data-border': true,
                  'data-framer-name': 'View Project'
                }
              },
              baseVariant,
              gestureVariant
            )}
          >
            {isDisplayed() && (
              <RichText
                __fromCanvasComponent={true}
                className={'framer-1npc8sa'}
                fonts={['GF;Inter-300']}
                layoutDependency={layoutDependency}
                layoutId={'aINE6FlLO'}
                style={{
                  '--extracted-r6o4lv':
                    'var(--token-528f84e0-f915-420f-bf60-2cbf77101a8e, rgb(255, 255, 255))',
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline'
                }}
                transformTemplate={transformTemplate1}
                verticalAlignment={'top'}
                withExternalLayout={true}
                {...addPropertyOverrides(
                  {
                    D8CGcjC8G: {
                      transformTemplate: void 0
                    }
                  },
                  baseVariant,
                  gestureVariant
                )}
              >
                <React.Fragment>
                  <motion.p
                    style={{
                      '--font-selector': 'R0Y7SW50ZXItMzAw',
                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                      '--framer-font-weight': '300',
                      '--framer-line-height': '0.8em',
                      '--framer-text-alignment': 'center',
                      '--framer-text-color':
                        'var(--extracted-r6o4lv, var(--token-528f84e0-f915-420f-bf60-2cbf77101a8e, rgb(255, 255, 255)))'
                    }}
                  >
                    {'View project'}
                  </motion.p>
                </React.Fragment>
              </RichText>
            )}
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-Rec7f.framer-11lcozp, .framer-Rec7f .framer-11lcozp { display: block; }',
  '.framer-Rec7f.framer-1lik2pt { height: 12px; overflow: hidden; position: relative; width: 12px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-Rec7f .framer-1npc8sa { flex: none; height: 12px; left: 50%; position: absolute; top: 68%; white-space: pre; width: auto; }',
  '.framer-Rec7f.framer-v-17zs766.framer-1lik2pt { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 16px 20px 16px 20px; width: min-content; }',
  '.framer-Rec7f.framer-v-17zs766 .framer-1npc8sa { left: unset; position: relative; top: unset; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Rec7f.framer-v-17zs766.framer-1lik2pt { gap: 0px; } .framer-Rec7f.framer-v-17zs766.framer-1lik2pt > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-Rec7f.framer-v-17zs766.framer-1lik2pt > :first-child { margin-left: 0px; } .framer-Rec7f.framer-v-17zs766.framer-1lik2pt > :last-child { margin-right: 0px; } }',
  '.framer-Rec7f[data-border="true"]::after, .framer-Rec7f [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'
];
var FramerTcjhCmN5c = withCSS(Component, css, 'framer-Rec7f');
var stdin_default = FramerTcjhCmN5c;
FramerTcjhCmN5c.displayName = 'Cursor';
FramerTcjhCmN5c.defaultProps = {
  height: 12,
  width: 12
};
addPropertyControls(FramerTcjhCmN5c, {
  variant: {
    options: ['N4TdUsQKx', 'D8CGcjC8G'],
    optionTitles: ['Default', 'View Project'],
    title: 'Variant',
    type: ControlType.Enum
  }
});
addFonts(
  FramerTcjhCmN5c,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'google',
          style: 'normal',
          url: 'https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuOKfMZ1rib2Bg-4.woff2',
          weight: '300'
        }
      ]
    }
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:cursor
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CursorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var cursor_default = ComponentWithRoot;
export { cursor_default as default };
