// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Hidden' // Variant
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from './chunks/chunk-NO3BJMB6.js';
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:load-more
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/nZkV4fEVqlvfN6gDtuvF/KPrFuHPkjvk6IpX2237C/jaqGrqxum.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
import { useRef } from 'react';
var MotionDivWithFX = withFX(motion.div);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(motion.div));
var cycleOrder = ['TuFsusb6K', 'jb8fMKPn6', 'oeVa65_5z'];
var serializationHash = 'framer-EI5g5';
var variantClassNames = {
  jb8fMKPn6: 'framer-v-ciwhoz',
  oeVa65_5z: 'framer-v-1nn7s06',
  TuFsusb6K: 'framer-v-1rytad8'
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = {
  duration: 0,
  type: 'tween'
};
var transition2 = {
  delay: 0,
  duration: 0.3,
  ease: [0.44, 0, 0.56, 1],
  type: 'tween'
};
var animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0
};
var animation1 = {
  opacity: 1e-3,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0
};
var transition3 = {
  delay: 0,
  duration: 1,
  ease: [0, 0, 1, 1],
  type: 'tween'
};
var animation2 = {
  opacity: 1,
  rotate: 360,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
  Default: 'TuFsusb6K',
  Hidden: 'oeVa65_5z',
  Loading: 'jb8fMKPn6'
};
var getProps = ({ click, height, id, width, ...props }) => {
  return {
    ...props,
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'TuFsusb6K',
    Wld3NDzSj: click ?? props.Wld3NDzSj
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className: className2,
    layoutId,
    variant,
    Wld3NDzSj,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'TuFsusb6K',
    ref: refBinding,
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onTapn9xadi = activeVariantCallback(async (...args) => {
    setGestureState({
      isPressed: false
    });
    if (Wld3NDzSj) {
      const res = await Wld3NDzSj(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [className];
  const isDisplayed = () => {
    if (baseVariant === 'oeVa65_5z') return false;
    return true;
  };
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed1 = () => {
    if (baseVariant === 'jb8fMKPn6') return false;
    return true;
  };
  const isDisplayed2 = () => {
    if (baseVariant === 'jb8fMKPn6') return true;
    return false;
  };
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        {isDisplayed() && (
          <Transition value={transition1}>
            <motion.div
              {...restProps}
              {...gestureHandlers}
              className={cx(scopingClassNames, 'framer-1rytad8', className2, classNames)}
              data-framer-name={'Default'}
              data-highlight={true}
              layoutDependency={layoutDependency}
              layoutId={'TuFsusb6K'}
              onTap={onTapn9xadi}
              ref={refBinding}
              style={{
                backgroundColor:
                  'var(--token-b2b2cec5-8316-4f9c-8fd9-5fdfc3c24032, rgba(255, 255, 255, 0.1))',
                borderBottomLeftRadius: 10,
                borderBottomRightRadius: 10,
                borderTopLeftRadius: 10,
                borderTopRightRadius: 10,
                ...style
              }}
              {...addPropertyOverrides(
                {
                  jb8fMKPn6: {
                    'data-framer-name': 'Loading'
                  }
                },
                baseVariant,
                gestureVariant
              )}
            >
              {isDisplayed1() && (
                <RichText
                  __fromCanvasComponent={true}
                  className={'framer-1r70i84'}
                  fonts={['Inter']}
                  layoutDependency={layoutDependency}
                  layoutId={'apbV68AcK'}
                  verticalAlignment={'top'}
                  withExternalLayout={true}
                >
                  <React.Fragment>
                    <motion.p
                      className={'framer-styles-preset-vp3sdo'}
                      data-styles-preset={'WQG2SsoyY'}
                    >
                      {'Load More'}
                    </motion.p>
                  </React.Fragment>
                </RichText>
              )}
              {isDisplayed2() && (
                <MotionDivWithFXWithOptimizedAppearEffect
                  __perspectiveFX={false}
                  __smartComponentFX={true}
                  __targetOpacity={1}
                  animate={animation}
                  className={'framer-1mmcsu9'}
                  data-framer-appear-id={'1mmcsu9'}
                  data-framer-name={'Spinner'}
                  initial={animation1}
                  layoutDependency={layoutDependency}
                  layoutId={'O92fXHVPK'}
                  optimized={true}
                  style={{
                    mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                    WebkitMask:
                      "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add"
                  }}
                >
                  <MotionDivWithFX
                    __framer__loop={animation2}
                    __framer__loopEffectEnabled={true}
                    __framer__loopRepeatDelay={0}
                    __framer__loopRepeatType={'loop'}
                    __framer__loopTransition={transition3}
                    __perspectiveFX={false}
                    __smartComponentFX={true}
                    __targetOpacity={1}
                    className={'framer-14dty0i'}
                    data-framer-name={'Conic'}
                    layoutDependency={layoutDependency}
                    layoutId={'jcDC9PpiA'}
                    style={{
                      background:
                        'conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 0deg, rgb(255, 255, 255) 342deg)'
                    }}
                  >
                    <motion.div
                      className={'framer-4sffcs'}
                      data-framer-name={'Round'}
                      layoutDependency={layoutDependency}
                      layoutId={'QZPwQ1zM8'}
                      style={{
                        backgroundColor: 'rgb(255, 255, 255)',
                        borderBottomLeftRadius: 1,
                        borderBottomRightRadius: 1,
                        borderTopLeftRadius: 1,
                        borderTopRightRadius: 1
                      }}
                    />
                  </MotionDivWithFX>
                </MotionDivWithFXWithOptimizedAppearEffect>
              )}
            </motion.div>
          </Transition>
        )}
      </Variants>
    </LayoutGroup>
  );
});
var css2 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-EI5g5.framer-1alu9f8, .framer-EI5g5 .framer-1alu9f8 { display: block; }',
  '.framer-EI5g5.framer-1rytad8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; padding: 0px; position: relative; width: 100px; }',
  '.framer-EI5g5 .framer-1r70i84 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }',
  '.framer-EI5g5 .framer-1mmcsu9 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); overflow: visible; position: relative; width: 20px; }',
  '.framer-EI5g5 .framer-14dty0i { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }',
  '.framer-EI5g5 .framer-4sffcs { flex: none; height: 2px; left: calc(50.00000000000002% - 2px / 2); overflow: visible; position: absolute; top: 0px; width: 2px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EI5g5.framer-1rytad8 { gap: 0px; } .framer-EI5g5.framer-1rytad8 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-EI5g5.framer-1rytad8 > :first-child { margin-left: 0px; } .framer-EI5g5.framer-1rytad8 > :last-child { margin-right: 0px; } }',
  ...css
];
var FramerjaqGrqxum = withCSS(Component, css2, 'framer-EI5g5');
var stdin_default = FramerjaqGrqxum;
FramerjaqGrqxum.displayName = 'Load More';
FramerjaqGrqxum.defaultProps = {
  height: 40,
  width: 100
};
addPropertyControls(FramerjaqGrqxum, {
  variant: {
    options: ['TuFsusb6K', 'jb8fMKPn6', 'oeVa65_5z'],
    optionTitles: ['Default', 'Loading', 'Hidden'],
    title: 'Variant',
    type: ControlType.Enum
  },
  Wld3NDzSj: {
    title: 'Click',
    type: ControlType.EventHandler
  }
});
addFonts(
  FramerjaqGrqxum,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400'
        }
      ]
    },
    ...getFontsFromSharedStyle(fonts)
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:load-more
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {
  base: 'TuFsusb6K'
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LoadMoreFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var load_more_default = ComponentWithRoot;
export { load_more_default as default };
