// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' | 'btn - glow off' // Variant
 * link?: string // Link
 * title?: string // Title
 * icon?: undefined // Icon
 * newTab?: boolean // New Tab
}} Props

 */
import { className, css, fonts } from './chunks/chunk-OVUOJGQZ.js';
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:main-button-2
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/wyXbWAlTqk1yT14bwrST/9CTYT1w7awqGulenAtam/UDXthURwJ.js
import { jsx as _jsx2, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls as addPropertyControls2,
  ControlType as ControlType2,
  cx as cx2,
  getFontsFromSharedStyle,
  Instance,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS as withCSS2
} from 'unframer';
import { LayoutGroup, motion as motion2, MotionConfigContext } from 'unframer';
import * as React2 from 'react';
import { useRef } from 'react';

// /:https://framerusercontent.com/modules/TgdovPTf12h5e9mf5mKX/ny0lQDjRQ5zoBlru0VHq/tL6Nru9eO.js
import { jsx as _jsx } from 'react/jsx-runtime';
import { addPropertyControls, ControlType, cx, motion, useSVGTemplate, withCSS } from 'unframer';
import * as React from 'react';
import { forwardRef as forwardRef2 } from 'react';
var mask = 'var(--framer-icon-mask)';
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
  return (
    <svg {...props} ref={ref}>
      {props.children}
    </svg>
  );
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated ? (
    <MotionSVG {...rest} layoutId={layoutId} ref={ref}>
      {children}
    </MotionSVG>
  ) : (
    <svg {...rest} ref={ref}>
      {children}
    </svg>
  );
});
var svg =
  '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0.75 C 0 0.336 0.336 0 0.75 0 L 15.75 0 C 16.164 0 16.5 0.336 16.5 0.75 L 16.5 15.75 C 16.5 16.164 16.164 16.5 15.75 16.5 L 0.75 16.5 C 0.336 16.5 0 16.164 0 15.75 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="16.5px" id="qUYSYEB2C" transform="translate(3.75 27.75)" width="16.5px"/><path d="M 0 0.75 C 0 0.336 0.336 0 0.75 0 L 15.75 0 C 16.164 0 16.5 0.336 16.5 0.75 L 16.5 15.75 C 16.5 16.164 16.164 16.5 15.75 16.5 L 0.75 16.5 C 0.336 16.5 0 16.164 0 15.75 Z" fill="transparent" height="16.5px" id="BcpYYi6FC" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3.75 27.75)" width="16.5px"/><path d="M 0 0 L 7.5 0" fill="transparent" height="1px" id="RQrRctFta" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 12)" width="7.5px"/><path d="M 0 0 L 3 3 L 0 6" fill="transparent" height="6px" id="qCkbhs0Cc" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(12.75 9)" width="3px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
  return {
    ...props,
    ezTt3ayMo: color ?? props.ezTt3ayMo ?? 'rgb(0, 0, 0)',
    lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
    qxTvv_EBh: alpha ?? props.qxTvv_EBh
  };
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const {
    style,
    className: className2,
    layoutId,
    variant,
    ezTt3ayMo,
    lschgej4H,
    qxTvv_EBh,
    ...restProps
  } = getProps(props);
  const href = useSVGTemplate('3855583215', svg);
  return (
    <SVG
      {...restProps}
      className={cx('framer-VHcoG', className2)}
      layoutId={layoutId}
      ref={ref}
      role={'presentation'}
      style={{
        '--1m6trwb': qxTvv_EBh,
        '--21h8s6': ezTt3ayMo,
        '--pgex8v': lschgej4H,
        ...style
      }}
      viewBox={'0 0 24 24'}
    >
      <use href={href} />
    </SVG>
  );
});
var css2 = [
  `.framer-VHcoG { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`
];
var Icon = withCSS(Component, css2, 'framer-VHcoG');
Icon.displayName = 'Arrow Square Right';
var stdin_default = Icon;
addPropertyControls(Icon, {
  ezTt3ayMo: {
    defaultValue: 'rgb(0, 0, 0)',
    hidden: false,
    title: 'Color',
    type: ControlType.Color
  },
  lschgej4H: {
    defaultValue: 1.5,
    displayStepper: true,
    hidden: false,
    max: 6,
    min: 0,
    step: 0.5,
    title: 'Width',
    type: ControlType.Number
  },
  qxTvv_EBh: {
    defaultValue: 0,
    displayStepper: true,
    hidden: false,
    max: 1,
    min: 0,
    step: 0.1,
    title: 'Alpha',
    type: ControlType.Number
  }
});

// /:https://framerusercontent.com/modules/wyXbWAlTqk1yT14bwrST/9CTYT1w7awqGulenAtam/UDXthURwJ.js
var enabledGestures = {
  Bw7I4rS2M: {
    hover: true
  },
  IEkXbrFK9: {
    hover: true
  },
  XQodMECIc: {
    hover: true
  }
};
var cycleOrder = ['Bw7I4rS2M', 'IEkXbrFK9', 'XQodMECIc'];
var serializationHash = 'framer-LLh1c';
var variantClassNames = {
  Bw7I4rS2M: 'framer-v-61gwd1',
  IEkXbrFK9: 'framer-v-17j25e',
  XQodMECIc: 'framer-v-1jpdt8a'
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = {
  damping: 100,
  delay: 0,
  mass: 1,
  stiffness: 255,
  type: 'spring'
};
var transition2 = {
  delay: 0,
  duration: 0.45,
  ease: [0.44, 0, 0.56, 1],
  type: 'tween'
};
var animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.8,
  skewX: 0,
  skewY: 0,
  transition: transition2
};
var animation1 = {
  filter: 'blur(10px)',
  opacity: 1e-3,
  rotate: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 10
};
var transition3 = {
  bounce: 0,
  delay: 0.05,
  duration: 0.4,
  type: 'spring'
};
var textEffect = {
  effect: animation1,
  threshold: 0.5,
  tokenization: 'character',
  transition: transition3,
  trigger: 'onInView',
  type: 'appear'
};
var transition4 = {
  bounce: 0.25,
  delay: 0,
  duration: 1.2,
  type: 'spring'
};
var animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1.1,
  skewX: 0,
  skewY: 0,
  transition: transition4
};
var transition5 = {
  bounce: 0.25,
  delay: 0,
  duration: 0.45,
  type: 'spring'
};
var animation3 = {
  opacity: 1,
  rotate: -34,
  rotateX: 0,
  rotateY: 0,
  scale: 1.4,
  skewX: 0,
  skewY: 0,
  transition: transition5
};
var animation4 = {
  opacity: 0.7,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1.5,
  skewX: 0,
  skewY: 0,
  transition: transition5
};
var Transition = ({ value, children }) => {
  const config = React2.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React2.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
  'btn - glow off': 'XQodMECIc',
  desktop: 'Bw7I4rS2M',
  mobile: 'IEkXbrFK9'
};
var getProps2 = ({ height, icon, id, link, newTab, title, width, ...props }) => {
  return {
    ...props,
    D_lQwlRhv: icon ?? props.D_lQwlRhv ?? stdin_default,
    pkd7Pcy3s: newTab ?? props.pkd7Pcy3s,
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'Bw7I4rS2M',
    WygjbYACO: title ?? props.WygjbYACO ?? 'View Products',
    ypOX2jdFN: link ?? props.ypOX2jdFN
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React2.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className: className2,
    layoutId,
    variant,
    ypOX2jdFN,
    WygjbYACO,
    D_lQwlRhv,
    pkd7Pcy3s,
    ...restProps
  } = getProps2(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'Bw7I4rS2M',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [className];
  const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === 'XQodMECIc-hover') return false;
    if (baseVariant === 'XQodMECIc') return false;
    return true;
  };
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link
            href={ypOX2jdFN}
            motionChild={true}
            nodeId={'Bw7I4rS2M'}
            openInNewTab={pkd7Pcy3s}
            scopeId={'UDXthURwJ'}
            smoothScroll={true}
          >
            <motion2.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx2(scopingClassNames, 'framer-61gwd1', className2, classNames)} framer-19by86e`}
              data-framer-name={'desktop'}
              layoutDependency={layoutDependency}
              layoutId={'Bw7I4rS2M'}
              ref={refBinding}
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                borderBottomLeftRadius: 8,
                borderBottomRightRadius: 8,
                borderTopLeftRadius: 8,
                borderTopRightRadius: 8,
                ...style
              }}
              {...addPropertyOverrides(
                {
                  'Bw7I4rS2M-hover': {
                    'data-framer-name': void 0
                  },
                  'IEkXbrFK9-hover': {
                    'data-framer-name': void 0
                  },
                  'XQodMECIc-hover': {
                    'data-framer-name': void 0
                  },
                  IEkXbrFK9: {
                    'data-framer-name': 'mobile'
                  },
                  XQodMECIc: {
                    'data-framer-name': 'btn - glow off'
                  }
                },
                baseVariant,
                gestureVariant
              )}
            >
              {isDisplayed() && (
                <motion2.div
                  className={'framer-1vd1mrj'}
                  data-framer-name={'Glow'}
                  layoutDependency={layoutDependency}
                  layoutId={'xHWm5l4mF'}
                  style={{
                    background:
                      'radial-gradient(25% 50% at 50% 100%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)',
                    borderBottomLeftRadius: 8,
                    borderBottomRightRadius: 8,
                    borderTopLeftRadius: 8,
                    borderTopRightRadius: 8,
                    filter: 'blur(15px)',
                    WebkitFilter: 'blur(15px)'
                  }}
                />
              )}
              {isDisplayed() && (
                <motion2.div
                  className={'framer-297pu3'}
                  data-framer-name={'Stroke'}
                  layoutDependency={layoutDependency}
                  layoutId={'DiVTijobr'}
                  style={{
                    background:
                      'radial-gradient(20.7% 50% at 50% 100%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)',
                    borderBottomLeftRadius: 8,
                    borderBottomRightRadius: 8,
                    borderTopLeftRadius: 8,
                    borderTopRightRadius: 8
                  }}
                  variants={{
                    'Bw7I4rS2M-hover': {
                      background:
                        'radial-gradient(60.099999999999994% 50% at 50% 100%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)'
                    }
                  }}
                />
              )}
              <motion2.div
                className={'framer-1agqlbw'}
                data-framer-name={'Fill'}
                layoutDependency={layoutDependency}
                layoutId={'HDHCVYXK5'}
                style={{
                  backgroundColor:
                    'var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0))',
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8
                }}
              />
              <motion2.div
                className={'framer-zssina'}
                data-framer-name={'text content'}
                layoutDependency={layoutDependency}
                layoutId={'AdxiCC1Cv'}
              >
                <RichText
                  __fromCanvasComponent={true}
                  className={'framer-15xpnk'}
                  data-framer-name={'Text'}
                  fonts={['Inter']}
                  layoutDependency={layoutDependency}
                  layoutId={'zweABeiOY'}
                  style={{
                    '--framer-link-text-color': 'rgb(0, 153, 255)',
                    '--framer-link-text-decoration': 'underline',
                    '--framer-paragraph-spacing': '0px'
                  }}
                  text={WygjbYACO}
                  verticalAlignment={'top'}
                  withExternalLayout={true}
                  {...addPropertyOverrides(
                    {
                      'XQodMECIc-hover': {
                        effect: textEffect,
                        whileHover: animation
                      }
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  <React2.Fragment>
                    <motion2.p
                      className={'framer-styles-preset-1uqxdd2'}
                      data-styles-preset={'uCnC2_tAh'}
                    >
                      {'Follow Me On'}
                    </motion2.p>
                  </React2.Fragment>
                </RichText>
                <Instance
                  animated={true}
                  className={'framer-1seltqm'}
                  Component={D_lQwlRhv}
                  layoutDependency={layoutDependency}
                  layoutId={'kyU3jmux_'}
                  style={{
                    '--1m6trwb': 0,
                    '--21h8s6':
                      'var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255))',
                    '--pgex8v': 1.5,
                    rotate: 0,
                    scale: 1.8
                  }}
                  variants={{
                    'Bw7I4rS2M-hover': {
                      rotate: -29
                    },
                    'IEkXbrFK9-hover': {
                      rotate: 0
                    },
                    'XQodMECIc-hover': {
                      rotate: 0
                    }
                  }}
                  {...addPropertyOverrides(
                    {
                      'Bw7I4rS2M-hover': {
                        whileHover: animation2
                      },
                      'IEkXbrFK9-hover': {
                        whileHover: animation3
                      },
                      'XQodMECIc-hover': {
                        whileHover: animation4
                      }
                    },
                    baseVariant,
                    gestureVariant
                  )}
                />
              </motion2.div>
            </motion2.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css3 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-LLh1c.framer-19by86e, .framer-LLh1c .framer-19by86e { display: block; }',
  '.framer-LLh1c.framer-61gwd1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 14px 28px 14px 28px; position: relative; text-decoration: none; width: min-content; }',
  '.framer-LLh1c .framer-1vd1mrj, .framer-LLh1c .framer-297pu3 { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 0; }',
  '.framer-LLh1c .framer-1agqlbw { bottom: 2px; flex: none; left: 2px; overflow: hidden; position: absolute; right: 2px; top: 2px; will-change: var(--framer-will-change-override, transform); z-index: 0; }',
  '.framer-LLh1c .framer-zssina { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }',
  '.framer-LLh1c .framer-15xpnk { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-LLh1c .framer-1seltqm { flex: none; height: var(--framer-aspect-ratio-supported, 22px); position: relative; width: 22px; }',
  '.framer-LLh1c.framer-v-61gwd1.hover .framer-1seltqm, .framer-LLh1c.framer-v-17j25e.hover .framer-1seltqm, .framer-LLh1c.framer-v-1jpdt8a.hover .framer-15xpnk, .framer-LLh1c.framer-v-1jpdt8a.hover .framer-1seltqm { will-change: var(--framer-will-change-effect-override, transform); }',
  ...css
];
var FramerUDXthURwJ = withCSS2(Component2, css3, 'framer-LLh1c');
var stdin_default2 = FramerUDXthURwJ;
FramerUDXthURwJ.displayName = 'main button 2';
FramerUDXthURwJ.defaultProps = {
  height: 60,
  width: 246.5
};
addPropertyControls2(FramerUDXthURwJ, {
  variant: {
    options: ['Bw7I4rS2M', 'IEkXbrFK9', 'XQodMECIc'],
    optionTitles: ['desktop', 'mobile', 'btn - glow off'],
    title: 'Variant',
    type: ControlType2.Enum
  },
  ypOX2jdFN: {
    title: 'Link',
    type: ControlType2.Link
  },
  WygjbYACO: {
    defaultValue: 'View Products',
    displayTextArea: false,
    title: 'Title',
    type: ControlType2.String
  },
  D_lQwlRhv: {
    defaultValue: {
      identifier: 'module:TgdovPTf12h5e9mf5mKX/ny0lQDjRQ5zoBlru0VHq/tL6Nru9eO.js:default',
      moduleId: 'TgdovPTf12h5e9mf5mKX'
    },
    setModuleId: 'omX0gWFPqDwhaiWwf6ab',
    title: 'Icon',
    type: ControlType2.VectorSetItem
  },
  pkd7Pcy3s: {
    defaultValue: false,
    title: 'New Tab',
    type: ControlType2.Boolean
  }
});
addFonts(
  FramerUDXthURwJ,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400'
        }
      ]
    },
    ...getFontsFromSharedStyle(fonts)
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:main-button-2
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {
  base: 'Bw7I4rS2M'
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default2, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainButton2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default2}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default2);
var main_button_2_default = ComponentWithRoot;
export { main_button_2_default as default };
