// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet/ Mobile' | 'Tablet/ Mobile Open' // Variant
}} Props

 */
import { stdin_default as stdin_default3 } from './chunks/chunk-PKLZBUHZ.js';
import { stdin_default as stdin_default2 } from './chunks/chunk-BFLVJTM4.js';
import { stdin_default } from './chunks/chunk-VFAEIFR6.js';
import './chunks/chunk-EITFHPVU.js';
import './chunks/chunk-BTSBQWPZ.js';
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:nav
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/dSK0pKesrqdaRh9RJIfJ/uLk4Vagzbiv8vHBFdtXI/WjZ4je_wS.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  ResolveLinks,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useRouter,
  useVariantState,
  withCSS
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
import { useRef } from 'react';
var MenuButtonFonts = getFonts(stdin_default);
var NavNavLinkFonts = getFonts(stdin_default3);
var SecondaryButtonFonts = getFonts(stdin_default2);
var cycleOrder = ['DASs5MXos', 'gKE67fZub', 'a3DUr8Kcj'];
var serializationHash = 'framer-uZ0c8';
var variantClassNames = {
  a3DUr8Kcj: 'framer-v-1ubwsoj',
  DASs5MXos: 'framer-v-7ui4vy',
  gKE67fZub: 'framer-v-18ihko2'
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: 'spring'
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
  'Tablet/ Mobile Open': 'a3DUr8Kcj',
  'Tablet/ Mobile': 'gKE67fZub',
  Desktop: 'DASs5MXos'
};
var getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'DASs5MXos'
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'DASs5MXos',
    ref: refBinding,
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onTapapvf8f = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('gKE67fZub'), 100);
  });
  const wFtRaEcWBd71e3b = activeVariantCallback(async (...args) => {
    setVariant('Va_5igiS1');
  });
  const wFtRaEcWBe0ocp8 = activeVariantCallback(async (...args) => {
    setVariant('a3DUr8Kcj');
  });
  const wFtRaEcWBxtggk9 = activeVariantCallback(async (...args) => {
    setVariant('gKE67fZub');
  });
  const kwWR1ZLuIapvf8f = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('gKE67fZub'), 100);
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (['gKE67fZub', 'a3DUr8Kcj'].includes(baseVariant)) return true;
    return false;
  };
  const router = useRouter();
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.nav
            {...restProps}
            {...gestureHandlers}
            className={cx(scopingClassNames, 'framer-7ui4vy', className, classNames)}
            data-border={true}
            data-framer-name={'Desktop'}
            layoutDependency={layoutDependency}
            layoutId={'DASs5MXos'}
            ref={refBinding}
            style={{
              '--border-bottom-width': '1px',
              '--border-color':
                'var(--token-b2b2cec5-8316-4f9c-8fd9-5fdfc3c24032, rgba(255, 255, 255, 0.1))',
              '--border-left-width': '1px',
              '--border-right-width': '1px',
              '--border-style': 'solid',
              '--border-top-width': '1px',
              backdropFilter: 'blur(12px)',
              backgroundColor:
                'var(--token-237a00c2-a8b1-4063-9fcb-8dc6bd0797dd, rgba(17, 17, 17, 0.7))',
              borderBottomLeftRadius: 32,
              borderBottomRightRadius: 32,
              borderTopLeftRadius: 32,
              borderTopRightRadius: 32,
              WebkitBackdropFilter: 'blur(12px)',
              ...style
            }}
            tabIndex={-1}
            variants={{
              a3DUr8Kcj: {
                backdropFilter: 'none',
                backgroundColor:
                  'var(--token-f5646347-2529-487d-8af1-d99f05c5451c, rgb(10, 10, 10))',
                WebkitBackdropFilter: 'none'
              },
              gKE67fZub: {
                backdropFilter: 'none',
                backgroundColor:
                  'var(--token-f5646347-2529-487d-8af1-d99f05c5451c, rgb(10, 10, 10))',
                WebkitBackdropFilter: 'none'
              }
            }}
            {...addPropertyOverrides(
              {
                a3DUr8Kcj: {
                  'data-framer-name': 'Tablet/ Mobile Open'
                },
                gKE67fZub: {
                  'data-framer-name': 'Tablet/ Mobile'
                }
              },
              baseVariant,
              gestureVariant
            )}
          >
            <motion.div
              className={'framer-beie2w'}
              data-framer-name={'Nav Wrapper'}
              layoutDependency={layoutDependency}
              layoutId={'ilda27tt1'}
            >
              <motion.div
                className={'framer-auuvt8'}
                data-framer-name={'Wrapper'}
                layoutDependency={layoutDependency}
                layoutId={'IKlqE8pLR'}
              >
                <Link
                  href={{
                    hash: ':LPH2zifzT',
                    webPageId: 'augiA20Il'
                  }}
                  motionChild={true}
                  nodeId={'oLrJJfd4M'}
                  openInNewTab={false}
                  scopeId={'WjZ4je_wS'}
                  smoothScroll={true}
                >
                  <Image
                    as={'a'}
                    background={{
                      alt: '',
                      fit: 'fit',
                      loading: getLoadingLazyAtYPosition(
                        (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 64) -
                              0 -
                              ((componentViewport?.height || 64) - 0) * 1) /
                              2) +
                          (0 + (((componentViewport?.height || 64) - 0) * 1 - 0 - 39) / 2) +
                          0
                      ),
                      pixelHeight: 100,
                      pixelWidth: 316,
                      positionX: 'left',
                      positionY: 'center',
                      src: 'https://framerusercontent.com/images/duRtoIIUg5pJHSrEAoXb5RLVCc.svg'
                    }}
                    className={'framer-1w4lwj4 framer-g9law'}
                    data-framer-name={'logo'}
                    layoutDependency={layoutDependency}
                    layoutId={'oLrJJfd4M'}
                    {...addPropertyOverrides(
                      {
                        a3DUr8Kcj: {
                          'data-highlight': true,
                          background: {
                            alt: '',
                            fit: 'fit',
                            pixelHeight: 100,
                            pixelWidth: 316,
                            positionX: 'left',
                            positionY: 'center',
                            src: 'https://framerusercontent.com/images/duRtoIIUg5pJHSrEAoXb5RLVCc.svg'
                          },
                          onTap: onTapapvf8f
                        },
                        gKE67fZub: {
                          background: {
                            alt: '',
                            fit: 'fit',
                            pixelHeight: 100,
                            pixelWidth: 316,
                            positionX: 'left',
                            positionY: 'center',
                            src: 'https://framerusercontent.com/images/duRtoIIUg5pJHSrEAoXb5RLVCc.svg'
                          }
                        }
                      },
                      baseVariant,
                      gestureVariant
                    )}
                  />
                </Link>
                {isDisplayed() && (
                  <ComponentViewportProvider
                    {...addPropertyOverrides(
                      {
                        a3DUr8Kcj: {
                          height: 36
                        },
                        gKE67fZub: {
                          height: 36
                        }
                      },
                      baseVariant,
                      gestureVariant
                    )}
                  >
                    <SmartComponentScopedContainer
                      className={'framer-12ze8jm-container'}
                      data-framer-name={'Mobile Menu Icon'}
                      layoutDependency={layoutDependency}
                      layoutId={'PDWkSdTlR-container'}
                      name={'Mobile Menu Icon'}
                      nodeId={'PDWkSdTlR'}
                      rendersWithMotion={true}
                      scopeId={'WjZ4je_wS'}
                    >
                      {_jsx(stdin_default, {
                        height: '100%',
                        id: 'PDWkSdTlR',
                        layoutId: 'PDWkSdTlR',
                        name: 'Mobile Menu Icon',
                        variant: 'eCAJUXREk',
                        wFtRaEcWB: wFtRaEcWBd71e3b,
                        width: '100%',
                        ...addPropertyOverrides(
                          {
                            a3DUr8Kcj: {
                              variant: 'lUqHrBod_',
                              wFtRaEcWB: wFtRaEcWBxtggk9
                            },
                            gKE67fZub: {
                              wFtRaEcWB: wFtRaEcWBe0ocp8
                            }
                          },
                          baseVariant,
                          gestureVariant
                        )
                      })}
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                )}
              </motion.div>
              <motion.div
                className={'framer-14grg2k'}
                data-framer-name={'Right Links'}
                layoutDependency={layoutDependency}
                layoutId={'lyxb7m34B'}
              >
                <motion.nav
                  className={'framer-65b4ht'}
                  data-framer-name={'nav links'}
                  layoutDependency={layoutDependency}
                  layoutId={'LVgNEZoRa'}
                >
                  <ResolveLinks
                    links={[
                      {
                        href: {
                          hash: ':CaAED2YD5',
                          webPageId: 'augiA20Il'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          hash: ':CaAED2YD5',
                          webPageId: 'augiA20Il'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          hash: ':CaAED2YD5',
                          webPageId: 'augiA20Il'
                        },
                        implicitPathVariables: void 0
                      }
                    ]}
                  >
                    {(resolvedLinks) => (
                      <ComponentViewportProvider
                        height={64}
                        y={
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 64) -
                              0 -
                              ((componentViewport?.height || 64) - 0) * 1) /
                              2) +
                          (0 + (((componentViewport?.height || 64) - 0) * 1 - 0 - 64) / 2) +
                          0 +
                          0
                        }
                        {...addPropertyOverrides(
                          {
                            a3DUr8Kcj: {
                              width: `min(${componentViewport?.width || '100vw'} - 36px, 1350px)`,
                              y: void 0
                            },
                            gKE67fZub: {
                              y: void 0
                            }
                          },
                          baseVariant,
                          gestureVariant
                        )}
                      >
                        <SmartComponentScopedContainer
                          className={'framer-1npidy0-container'}
                          layoutDependency={layoutDependency}
                          layoutId={'HN2n5Js6j-container'}
                          nodeId={'HN2n5Js6j'}
                          rendersWithMotion={true}
                          scopeId={'WjZ4je_wS'}
                        >
                          {_jsx(stdin_default3, {
                            fF32h_OBQ: 'Services',
                            height: '100%',
                            id: 'HN2n5Js6j',
                            layoutId: 'HN2n5Js6j',
                            Mm9yYAj7D: resolvedLinks[0],
                            width: '100%',
                            ...addPropertyOverrides(
                              {
                                a3DUr8Kcj: {
                                  kwWR1ZLuI: kwWR1ZLuIapvf8f,
                                  Mm9yYAj7D: resolvedLinks[2],
                                  style: {
                                    width: '100%'
                                  }
                                },
                                gKE67fZub: {
                                  Mm9yYAj7D: resolvedLinks[1]
                                }
                              },
                              baseVariant,
                              gestureVariant
                            )
                          })}
                        </SmartComponentScopedContainer>
                      </ComponentViewportProvider>
                    )}
                  </ResolveLinks>
                  <ResolveLinks
                    links={[
                      {
                        href: {
                          webPageId: 'KZiBMHKVh'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          webPageId: 'KZiBMHKVh'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          webPageId: 'KZiBMHKVh'
                        },
                        implicitPathVariables: void 0
                      }
                    ]}
                  >
                    {(resolvedLinks1) => (
                      <ComponentViewportProvider
                        height={64}
                        y={
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 64) -
                              0 -
                              ((componentViewport?.height || 64) - 0) * 1) /
                              2) +
                          (0 + (((componentViewport?.height || 64) - 0) * 1 - 0 - 64) / 2) +
                          0 +
                          0
                        }
                        {...addPropertyOverrides(
                          {
                            a3DUr8Kcj: {
                              width: `min(${componentViewport?.width || '100vw'} - 36px, 1350px)`,
                              y: void 0
                            },
                            gKE67fZub: {
                              y: void 0
                            }
                          },
                          baseVariant,
                          gestureVariant
                        )}
                      >
                        <SmartComponentScopedContainer
                          className={'framer-d513k-container'}
                          layoutDependency={layoutDependency}
                          layoutId={'QpusnZ7c0-container'}
                          nodeId={'QpusnZ7c0'}
                          rendersWithMotion={true}
                          scopeId={'WjZ4je_wS'}
                        >
                          {_jsx(stdin_default3, {
                            fF32h_OBQ: 'Projects',
                            height: '100%',
                            id: 'QpusnZ7c0',
                            layoutId: 'QpusnZ7c0',
                            Mm9yYAj7D: resolvedLinks1[0],
                            width: '100%',
                            ...addPropertyOverrides(
                              {
                                a3DUr8Kcj: {
                                  kwWR1ZLuI: kwWR1ZLuIapvf8f,
                                  Mm9yYAj7D: resolvedLinks1[2],
                                  style: {
                                    width: '100%'
                                  }
                                },
                                gKE67fZub: {
                                  Mm9yYAj7D: resolvedLinks1[1]
                                }
                              },
                              baseVariant,
                              gestureVariant
                            )
                          })}
                        </SmartComponentScopedContainer>
                      </ComponentViewportProvider>
                    )}
                  </ResolveLinks>
                  <ResolveLinks
                    links={[
                      {
                        href: {
                          hash: ':b58gIVT3I',
                          webPageId: 'augiA20Il'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          hash: ':b58gIVT3I',
                          webPageId: 'augiA20Il'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          hash: ':b58gIVT3I',
                          webPageId: 'augiA20Il'
                        },
                        implicitPathVariables: void 0
                      }
                    ]}
                  >
                    {(resolvedLinks2) => (
                      <ComponentViewportProvider
                        height={64}
                        y={
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 64) -
                              0 -
                              ((componentViewport?.height || 64) - 0) * 1) /
                              2) +
                          (0 + (((componentViewport?.height || 64) - 0) * 1 - 0 - 64) / 2) +
                          0 +
                          0
                        }
                        {...addPropertyOverrides(
                          {
                            a3DUr8Kcj: {
                              width: `min(${componentViewport?.width || '100vw'} - 36px, 1350px)`,
                              y: void 0
                            },
                            gKE67fZub: {
                              y: void 0
                            }
                          },
                          baseVariant,
                          gestureVariant
                        )}
                      >
                        <SmartComponentScopedContainer
                          className={'framer-1hho832-container'}
                          layoutDependency={layoutDependency}
                          layoutId={'o_k5RhvJW-container'}
                          nodeId={'o_k5RhvJW'}
                          rendersWithMotion={true}
                          scopeId={'WjZ4je_wS'}
                        >
                          {_jsx(stdin_default3, {
                            fF32h_OBQ: 'Testimonials',
                            height: '100%',
                            id: 'o_k5RhvJW',
                            layoutId: 'o_k5RhvJW',
                            Mm9yYAj7D: resolvedLinks2[0],
                            width: '100%',
                            ...addPropertyOverrides(
                              {
                                a3DUr8Kcj: {
                                  kwWR1ZLuI: kwWR1ZLuIapvf8f,
                                  Mm9yYAj7D: resolvedLinks2[2],
                                  style: {
                                    width: '100%'
                                  }
                                },
                                gKE67fZub: {
                                  Mm9yYAj7D: resolvedLinks2[1]
                                }
                              },
                              baseVariant,
                              gestureVariant
                            )
                          })}
                        </SmartComponentScopedContainer>
                      </ComponentViewportProvider>
                    )}
                  </ResolveLinks>
                  <ResolveLinks
                    links={[
                      {
                        href: {
                          webPageId: 'mMBXPq2dS'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          webPageId: 'mMBXPq2dS'
                        },
                        implicitPathVariables: void 0
                      },
                      {
                        href: {
                          webPageId: 'mMBXPq2dS'
                        },
                        implicitPathVariables: void 0
                      }
                    ]}
                  >
                    {(resolvedLinks3) => (
                      <ComponentViewportProvider
                        height={64}
                        y={
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 64) -
                              0 -
                              ((componentViewport?.height || 64) - 0) * 1) /
                              2) +
                          (0 + (((componentViewport?.height || 64) - 0) * 1 - 0 - 64) / 2) +
                          0 +
                          0
                        }
                        {...addPropertyOverrides(
                          {
                            a3DUr8Kcj: {
                              width: `min(${componentViewport?.width || '100vw'} - 36px, 1350px)`,
                              y: void 0
                            },
                            gKE67fZub: {
                              y: void 0
                            }
                          },
                          baseVariant,
                          gestureVariant
                        )}
                      >
                        <SmartComponentScopedContainer
                          className={'framer-t5vekd-container'}
                          layoutDependency={layoutDependency}
                          layoutId={'gLxao_lV5-container'}
                          nodeId={'gLxao_lV5'}
                          rendersWithMotion={true}
                          scopeId={'WjZ4je_wS'}
                        >
                          {_jsx(stdin_default3, {
                            fF32h_OBQ: 'Contact',
                            height: '100%',
                            id: 'gLxao_lV5',
                            layoutId: 'gLxao_lV5',
                            Mm9yYAj7D: resolvedLinks3[0],
                            width: '100%',
                            ...addPropertyOverrides(
                              {
                                a3DUr8Kcj: {
                                  kwWR1ZLuI: kwWR1ZLuIapvf8f,
                                  Mm9yYAj7D: resolvedLinks3[2],
                                  style: {
                                    width: '100%'
                                  }
                                },
                                gKE67fZub: {
                                  Mm9yYAj7D: resolvedLinks3[1]
                                }
                              },
                              baseVariant,
                              gestureVariant
                            )
                          })}
                        </SmartComponentScopedContainer>
                      </ComponentViewportProvider>
                    )}
                  </ResolveLinks>
                </motion.nav>
                <ComponentViewportProvider
                  height={48}
                  y={
                    (componentViewport?.y || 0) +
                    (0 +
                      ((componentViewport?.height || 64) -
                        0 -
                        ((componentViewport?.height || 64) - 0) * 1) /
                        2) +
                    (0 + (((componentViewport?.height || 64) - 0) * 1 - 0 - 64) / 2) +
                    8
                  }
                  {...addPropertyOverrides(
                    {
                      a3DUr8Kcj: {
                        y: void 0
                      },
                      gKE67fZub: {
                        y: void 0
                      }
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  <SmartComponentScopedContainer
                    className={'framer-16tze6d-container'}
                    layoutDependency={layoutDependency}
                    layoutId={'zXtngsYZ2-container'}
                    nodeId={'zXtngsYZ2'}
                    rendersWithMotion={true}
                    scopeId={'WjZ4je_wS'}
                  >
                    {_jsx(stdin_default2, {
                      height: '100%',
                      id: 'zXtngsYZ2',
                      layoutId: 'zXtngsYZ2',
                      Ou2Q7KKjz: true,
                      QLeYG_zlf: 'Sparkle',
                      tIpm2Fclc: 'Get for Free',
                      vabCwIWAm: 'https://framer.link/rioO8iI',
                      width: '100%'
                    })}
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </motion.div>
            </motion.div>
          </motion.nav>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-uZ0c8.framer-g9law, .framer-uZ0c8 .framer-g9law { display: block; }',
  '.framer-uZ0c8.framer-7ui4vy { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 64px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 840px; }',
  '.framer-uZ0c8 .framer-beie2w { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: 100%; justify-content: flex-start; max-width: 1350px; overflow: visible; padding: 0px 40px 0px 40px; position: relative; width: 1px; }',
  '.framer-uZ0c8 .framer-auuvt8 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }',
  '.framer-uZ0c8 .framer-1w4lwj4 { flex: none; height: 39px; overflow: visible; position: relative; text-decoration: none; width: 80px; }',
  '.framer-uZ0c8 .framer-12ze8jm-container, .framer-uZ0c8 .framer-1npidy0-container, .framer-uZ0c8 .framer-d513k-container, .framer-uZ0c8 .framer-1hho832-container, .framer-uZ0c8 .framer-t5vekd-container, .framer-uZ0c8 .framer-16tze6d-container { flex: none; height: auto; position: relative; width: auto; }',
  '.framer-uZ0c8 .framer-14grg2k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }',
  '.framer-uZ0c8 .framer-65b4ht { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }',
  '.framer-uZ0c8.framer-v-18ihko2.framer-7ui4vy { align-content: flex-start; align-items: flex-start; flex-wrap: wrap; overflow: hidden; width: 390px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-uZ0c8.framer-v-18ihko2 .framer-beie2w { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 8px; height: 64px; padding: 0px 18px 32px 18px; }',
  '.framer-uZ0c8.framer-v-18ihko2 .framer-auuvt8, .framer-uZ0c8.framer-v-1ubwsoj .framer-auuvt8 { flex: none; gap: unset; height: 64px; justify-content: space-between; width: 100%; }',
  '.framer-uZ0c8.framer-v-18ihko2 .framer-14grg2k, .framer-uZ0c8.framer-v-18ihko2 .framer-65b4ht, .framer-uZ0c8.framer-v-1ubwsoj .framer-14grg2k { align-content: flex-start; align-items: flex-start; flex-direction: column; width: 100%; }',
  '.framer-uZ0c8.framer-v-1ubwsoj.framer-7ui4vy { align-content: flex-start; align-items: flex-start; flex-wrap: wrap; height: min-content; overflow: hidden; padding: 0px 18px 32px 18px; width: 390px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-uZ0c8.framer-v-1ubwsoj .framer-beie2w { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 8px; height: min-content; padding: 0px 0px 32px 0px; }',
  '.framer-uZ0c8.framer-v-1ubwsoj .framer-1w4lwj4 { cursor: pointer; }',
  '.framer-uZ0c8.framer-v-1ubwsoj .framer-65b4ht { flex-direction: column; width: 100%; }',
  '.framer-uZ0c8.framer-v-1ubwsoj .framer-1npidy0-container, .framer-uZ0c8.framer-v-1ubwsoj .framer-d513k-container, .framer-uZ0c8.framer-v-1ubwsoj .framer-1hho832-container, .framer-uZ0c8.framer-v-1ubwsoj .framer-t5vekd-container { width: 100%; }',
  '.framer-uZ0c8[data-border="true"]::after, .framer-uZ0c8 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'
];
var FramerWjZ4je_wS = withCSS(Component, css, 'framer-uZ0c8');
var stdin_default4 = FramerWjZ4je_wS;
FramerWjZ4je_wS.displayName = 'Nav';
FramerWjZ4je_wS.defaultProps = {
  height: 64,
  width: 840
};
addPropertyControls(FramerWjZ4je_wS, {
  variant: {
    options: ['DASs5MXos', 'gKE67fZub', 'a3DUr8Kcj'],
    optionTitles: ['Desktop', 'Tablet/ Mobile', 'Tablet/ Mobile Open'],
    title: 'Variant',
    type: ControlType.Enum
  }
});
addFonts(
  FramerWjZ4je_wS,
  [
    {
      explicitInter: true,
      fonts: []
    },
    ...MenuButtonFonts,
    ...NavNavLinkFonts,
    ...SecondaryButtonFonts
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:nav
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default4, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default4}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default4);
var nav_default = ComponentWithRoot;
export { nav_default as default };
