// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary' | 'bento variant' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * link?: string // Link
}} Props

 */
import { Icon } from './chunks/chunk-BTSBQWPZ.js';
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:project-card
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/4iXGltAFmRgrrE1i0twq/PaoiaY7NeSkintMiZAAF/bGyBygDVJ.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
import { useRef } from 'react';
var PhosphorFonts = getFonts(Icon);
var MotionAWithFX = withFX(motion.a);
var enabledGestures = {
  GsyVU7Fpu: {
    hover: true
  },
  O7DE6TNME: {
    hover: true
  }
};
var cycleOrder = ['GsyVU7Fpu', 'O7DE6TNME'];
var serializationHash = 'framer-eEQqN';
var variantClassNames = {
  GsyVU7Fpu: 'framer-v-1skrgfi',
  O7DE6TNME: 'framer-v-kspx97'
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: -50,
  y: 0
};
var transition1 = {
  damping: 25,
  delay: 0.1,
  mass: 1,
  stiffness: 127,
  type: 'spring'
};
var animation1 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: -50,
  y: 0
};
var transition2 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 400,
  type: 'spring'
};
var toResponsiveImage = (value) => {
  if (typeof value === 'object' && value !== null && typeof value.src === 'string') {
    return value;
  }
  return typeof value === 'string'
    ? {
        src: value
      }
    : void 0;
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
  'bento variant': 'O7DE6TNME',
  Primary: 'GsyVU7Fpu'
};
var getProps = ({ height, id, image, link, width, ...props }) => {
  return {
    ...props,
    LllLN7r46: link ?? props.LllLN7r46,
    spkf1SfwF: image ??
      props.spkf1SfwF ?? {
        pixelHeight: 800,
        pixelWidth: 800,
        src: 'https://framerusercontent.com/images/w6q75rhuZwsRoLIyc3C2zJ5oybY.webp?width=800&height=800',
        srcSet:
          'https://framerusercontent.com/images/w6q75rhuZwsRoLIyc3C2zJ5oybY.webp?scale-down-to=512&width=800&height=800 512w,https://framerusercontent.com/images/w6q75rhuZwsRoLIyc3C2zJ5oybY.webp?width=800&height=800 800w'
      },
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'GsyVU7Fpu'
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, spkf1SfwF, LllLN7r46, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'GsyVU7Fpu',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition2}>
          <Link
            href={LllLN7r46}
            motionChild={true}
            nodeId={'GsyVU7Fpu'}
            openInNewTab={false}
            scopeId={'bGyBygDVJ'}
          >
            <MotionAWithFX
              {...restProps}
              {...gestureHandlers}
              __framer__animate={{
                transition: transition1
              }}
              __framer__animateOnce={true}
              __framer__enter={animation}
              __framer__exit={animation1}
              __framer__styleAppearEffectEnabled={true}
              __framer__threshold={0}
              __perspectiveFX={false}
              __smartComponentFX={true}
              __targetOpacity={1}
              className={`${cx(scopingClassNames, 'framer-1skrgfi', className, classNames)} framer-9kazhr`}
              data-framer-name={'Primary'}
              layoutDependency={layoutDependency}
              layoutId={'GsyVU7Fpu'}
              ref={refBinding}
              style={{
                backgroundColor:
                  'var(--token-cba3b9c8-9e49-437e-aca1-1e69db3088dc, rgb(17, 17, 17))',
                borderBottomLeftRadius: 20,
                borderBottomRightRadius: 20,
                borderTopLeftRadius: 20,
                borderTopRightRadius: 20,
                boxShadow:
                  '16px 24px 20px 8px rgba(0, 0, 0, 0.4), inset 0px 2px 0px 0px rgba(184, 180, 180, 0.08)',
                ...style
              }}
              {...addPropertyOverrides(
                {
                  'GsyVU7Fpu-hover': {
                    'data-framer-name': void 0
                  },
                  'O7DE6TNME-hover': {
                    'data-framer-name': void 0
                  },
                  O7DE6TNME: {
                    'data-framer-name': 'bento variant'
                  }
                },
                baseVariant,
                gestureVariant
              )}
            >
              <motion.div
                className={'framer-103apa5'}
                data-framer-name={'Image container'}
                layoutDependency={layoutDependency}
                layoutId={'jpPYWolpa'}
                style={{
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8
                }}
              >
                <Image
                  background={{
                    alt: '',
                    fit: 'fill',
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) +
                        20 +
                        (((componentViewport?.height || 435) - 40 - 395) / 2 + 0 + 0) +
                        0
                    ),
                    pixelHeight: 800,
                    pixelWidth: 800,
                    sizes: `max(${componentViewport?.width || '100vw'} - 40px, 1px)`,
                    ...toResponsiveImage(spkf1SfwF)
                  }}
                  className={'framer-nnkl5n'}
                  layoutDependency={layoutDependency}
                  layoutId={'qfyR_L_iL'}
                  style={{
                    boxShadow: '20px 30px 20px 8px rgba(0, 0, 0, 0.4)',
                    scale: 1
                  }}
                  variants={{
                    'GsyVU7Fpu-hover': {
                      scale: 1.05
                    },
                    'O7DE6TNME-hover': {
                      scale: 1
                    }
                  }}
                  {...addPropertyOverrides(
                    {
                      O7DE6TNME: {
                        background: {
                          alt: '',
                          fit: 'fill',
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              20 +
                              (((componentViewport?.height || 661) -
                                40 -
                                (Math.max(0, ((componentViewport?.height || 661) - 40 - 0) / 1) *
                                  1 +
                                  0)) /
                                2 +
                                0 +
                                0) +
                              (0 +
                                (Math.max(0, ((componentViewport?.height || 661) - 40 - 0) / 1) *
                                  1 -
                                  0 -
                                  (Math.max(0, ((componentViewport?.height || 661) - 40 - 0) / 1) *
                                    1 -
                                    0) *
                                    1) /
                                  2)
                          ),
                          pixelHeight: 800,
                          pixelWidth: 800,
                          sizes: `max(${componentViewport?.width || '100vw'} - 40px, 1px)`,
                          ...toResponsiveImage(spkf1SfwF),
                          ...{
                            positionX: 'left',
                            positionY: 'center'
                          }
                        }
                      }
                    },
                    baseVariant,
                    gestureVariant
                  )}
                />
              </motion.div>
              <motion.div
                className={'framer-17osbco'}
                data-framer-name={'Icon'}
                layoutDependency={layoutDependency}
                layoutId={'O1NVs0tFo'}
                style={{
                  backgroundColor:
                    'var(--token-f5646347-2529-487d-8af1-d99f05c5451c, rgb(10, 10, 10))',
                  borderBottomLeftRadius: 100,
                  borderBottomRightRadius: 100,
                  borderTopLeftRadius: 100,
                  borderTopRightRadius: 100,
                  rotate: -35
                }}
              >
                <ComponentViewportProvider>
                  <SmartComponentScopedContainer
                    className={'framer-nzchhw-container'}
                    isAuthoredByUser={true}
                    isModuleExternal={true}
                    layoutDependency={layoutDependency}
                    layoutId={'IN7MG9RHP-container'}
                    nodeId={'IN7MG9RHP'}
                    rendersWithMotion={true}
                    scopeId={'bGyBygDVJ'}
                  >
                    <Icon
                      color={
                        'var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))'
                      }
                      height={'100%'}
                      iconSearch={'House'}
                      iconSelection={'ArrowRight'}
                      id={'IN7MG9RHP'}
                      layoutId={'IN7MG9RHP'}
                      mirrored={false}
                      selectByList={true}
                      style={{
                        height: '100%',
                        width: '100%'
                      }}
                      weight={'regular'}
                      width={'100%'}
                    />
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
                <ComponentViewportProvider>
                  <SmartComponentScopedContainer
                    className={'framer-1v0atpl-container'}
                    isAuthoredByUser={true}
                    isModuleExternal={true}
                    layoutDependency={layoutDependency}
                    layoutId={'oM4_NYTGB-container'}
                    nodeId={'oM4_NYTGB'}
                    rendersWithMotion={true}
                    scopeId={'bGyBygDVJ'}
                  >
                    <Icon
                      color={'rgb(255, 255, 255)'}
                      height={'100%'}
                      iconSearch={'House'}
                      iconSelection={'ArrowRight'}
                      id={'oM4_NYTGB'}
                      layoutId={'oM4_NYTGB'}
                      mirrored={false}
                      selectByList={true}
                      style={{
                        height: '100%',
                        width: '100%'
                      }}
                      weight={'regular'}
                      width={'100%'}
                    />
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </motion.div>
            </MotionAWithFX>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-eEQqN.framer-9kazhr, .framer-eEQqN .framer-9kazhr { display: block; }',
  '.framer-eEQqN.framer-1skrgfi { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 20px; position: relative; text-decoration: none; width: 638px; }',
  '.framer-eEQqN .framer-103apa5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }',
  '.framer-eEQqN .framer-nnkl5n { aspect-ratio: 1.5139240506329115 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 395px); position: relative; width: 1px; }',
  '.framer-eEQqN .framer-17osbco { align-content: center; align-items: center; bottom: 12px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 7px; overflow: hidden; padding: 11px; position: absolute; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: 1; }',
  '.framer-eEQqN .framer-nzchhw-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 28px); position: relative; width: 25px; }',
  '.framer-eEQqN .framer-1v0atpl-container { aspect-ratio: 1 / 1; bottom: -22px; flex: none; height: var(--framer-aspect-ratio-supported, 28px); left: -22px; position: absolute; width: 25px; z-index: 1; }',
  '.framer-eEQqN.framer-v-kspx97.framer-1skrgfi { height: 661px; width: 666px; }',
  '.framer-eEQqN.framer-v-kspx97 .framer-103apa5 { flex: 1 0 0px; height: 1px; }',
  '.framer-eEQqN.framer-v-kspx97 .framer-nnkl5n { aspect-ratio: unset; height: 100%; }',
  '.framer-eEQqN.framer-v-1skrgfi.hover .framer-nnkl5n { order: 0; }',
  '.framer-eEQqN.framer-v-1skrgfi.hover .framer-nzchhw-container, .framer-eEQqN.framer-v-kspx97.hover .framer-nzchhw-container { position: absolute; right: -22px; top: -22px; z-index: 1; }',
  '.framer-eEQqN.framer-v-1skrgfi.hover .framer-1v0atpl-container, .framer-eEQqN.framer-v-kspx97.hover .framer-1v0atpl-container { bottom: unset; left: unset; position: relative; }',
  '.framer-eEQqN.framer-v-kspx97.hover .framer-nnkl5n { aspect-ratio: unset; }'
];
var FramerbGyBygDVJ = withCSS(Component, css, 'framer-eEQqN');
var stdin_default = FramerbGyBygDVJ;
FramerbGyBygDVJ.displayName = 'project card';
FramerbGyBygDVJ.defaultProps = {
  height: 435,
  width: 638
};
addPropertyControls(FramerbGyBygDVJ, {
  variant: {
    options: ['GsyVU7Fpu', 'O7DE6TNME'],
    optionTitles: ['Primary', 'bento variant'],
    title: 'Variant',
    type: ControlType.Enum
  },
  spkf1SfwF: {
    __defaultAssetReference:
      'data:framer/asset-reference,w6q75rhuZwsRoLIyc3C2zJ5oybY.webp?originalFilename=FAS-nitrous-charger-build.webp&width=800&height=800',
    title: 'Image',
    type: ControlType.ResponsiveImage
  },
  LllLN7r46: {
    title: 'Link',
    type: ControlType.Link
  }
});
addFonts(
  FramerbGyBygDVJ,
  [
    {
      explicitInter: true,
      fonts: []
    },
    ...PhosphorFonts
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:project-card
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {
  base: 'GsyVU7Fpu'
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var project_card_default = ComponentWithRoot;
export { project_card_default as default };
