// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary' | 'No Separator Line' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * userName?: string // User name
 * company?: string // Company
 * rating?: number // Rating
 * review?: string // review
}} Props

 */
import { StarRating } from './chunks/chunk-RQG74B6P.js';
import { className as className2, css as css2, fonts as fonts2 } from './chunks/chunk-NO3BJMB6.js';
import { className, css, fonts } from './chunks/chunk-EITFHPVU.js';
import { className as className3, css as css3, fonts as fonts3 } from './chunks/chunk-F3ACLJ4N.js';
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:review
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/w67N38eCRQycfjE9bL39/m7CG5AmUsccuRXyVcVIK/sMosg71Yw.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
import { useRef } from 'react';
var StarRatingFonts = getFonts(StarRating);
var cycleOrder = ['Dv19BtwkD', 'MyqbbbqiE'];
var serializationHash = 'framer-UHQgu';
var variantClassNames = {
  Dv19BtwkD: 'framer-v-ofwhdh',
  MyqbbbqiE: 'framer-v-lwphx1'
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: 'spring'
};
var toResponsiveImage = (value) => {
  if (typeof value === 'object' && value !== null && typeof value.src === 'string') {
    return value;
  }
  return typeof value === 'string'
    ? {
        src: value
      }
    : void 0;
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
  'No Separator Line': 'MyqbbbqiE',
  Primary: 'Dv19BtwkD'
};
var getProps = ({ company, height, id, image, rating, review, userName, width, ...props }) => {
  return {
    ...props,
    EDZrlkgJD: company ?? props.EDZrlkgJD ?? 'Stephen sures',
    I2vY11AUy: image ?? props.I2vY11AUy,
    mp9KLmAEX: rating ?? props.mp9KLmAEX ?? 5,
    P7P_MrujI: userName ?? props.P7P_MrujI ?? 'Kenny Stephen',
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'Dv19BtwkD',
    ya3Sv_foF:
      review ??
      props.ya3Sv_foF ??
      'Start building your sites without any stress using the landerkit now, and if you have any doubts please feel free to reach out'
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className: className4,
    layoutId,
    variant,
    I2vY11AUy,
    P7P_MrujI,
    EDZrlkgJD,
    mp9KLmAEX,
    ya3Sv_foF,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'Dv19BtwkD',
    ref: refBinding,
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [className3, className, className2];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === 'MyqbbbqiE') return false;
    return true;
  };
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(scopingClassNames, 'framer-ofwhdh', className4, classNames)}
            data-framer-name={'Primary'}
            layoutDependency={layoutDependency}
            layoutId={'Dv19BtwkD'}
            ref={refBinding}
            style={{
              background:
                'linear-gradient(121deg, var(--token-16f2e642-57af-452f-984c-64067596f797, rgb(120, 120, 120)) /* {"name":"light grey"} */ -52%, var(--token-cba3b9c8-9e49-437e-aca1-1e69db3088dc, rgb(17, 17, 17)) /* {"name":"Dark Background Color"} */ 19%, var(--token-f5646347-2529-487d-8af1-d99f05c5451c, rgb(10, 10, 10)) /* {"name":"Background"} */ 100%)',
              borderBottomLeftRadius: 16,
              borderBottomRightRadius: 16,
              borderTopLeftRadius: 16,
              borderTopRightRadius: 16,
              boxShadow: 'inset 0px 2px 0px 0px rgba(184, 180, 180, 0.08)',
              ...style
            }}
            {...addPropertyOverrides(
              {
                MyqbbbqiE: {
                  'data-framer-name': 'No Separator Line'
                }
              },
              baseVariant,
              gestureVariant
            )}
          >
            <motion.div
              className={'framer-1dka7ig'}
              data-framer-name={'profile & text'}
              layoutDependency={layoutDependency}
              layoutId={'J1VHvwQGx'}
            >
              <motion.div
                className={'framer-8q5y6o'}
                data-framer-name={'content'}
                layoutDependency={layoutDependency}
                layoutId={'Yg_qyc6Ny'}
              >
                <Image
                  background={{
                    alt: '',
                    fit: 'fill',
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) +
                        24 +
                        (((componentViewport?.height || 296) - 48 - 611) / 2 + 0 + 0) +
                        0 +
                        63.5
                    ),
                    sizes: '76px',
                    ...toResponsiveImage(I2vY11AUy),
                    ...{
                      positionX: 'center',
                      positionY: 'center'
                    }
                  }}
                  className={'framer-122ls07'}
                  layoutDependency={layoutDependency}
                  layoutId={'IWv3kWbd1'}
                  style={{
                    borderBottomLeftRadius: 8,
                    borderBottomRightRadius: 8,
                    borderTopLeftRadius: 8,
                    borderTopRightRadius: 8
                  }}
                  {...addPropertyOverrides(
                    {
                      MyqbbbqiE: {
                        background: {
                          alt: '',
                          fit: 'fill',
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              24 +
                              (((componentViewport?.height || 271) - 48 - 586) / 2 + 0 + 0) +
                              0 +
                              63.5
                          ),
                          sizes: '76px',
                          ...toResponsiveImage(I2vY11AUy),
                          ...{
                            positionX: 'center',
                            positionY: 'center'
                          }
                        }
                      }
                    },
                    baseVariant,
                    gestureVariant
                  )}
                />
                <motion.div
                  className={'framer-7civ38'}
                  data-framer-name={'text'}
                  layoutDependency={layoutDependency}
                  layoutId={'uAlbIe1aw'}
                >
                  <RichText
                    __fromCanvasComponent={true}
                    className={'framer-1p6g420'}
                    fonts={['Inter']}
                    layoutDependency={layoutDependency}
                    layoutId={'hunChwDJv'}
                    style={{
                      '--framer-link-text-color': 'rgb(0, 153, 255)',
                      '--framer-link-text-decoration': 'underline'
                    }}
                    text={P7P_MrujI}
                    verticalAlignment={'top'}
                    withExternalLayout={true}
                  >
                    <React.Fragment>
                      <motion.h4
                        className={'framer-styles-preset-1o2kbzs'}
                        data-styles-preset={'HglFp_qS2'}
                      >
                        {'Kenny Stephen'}
                      </motion.h4>
                    </React.Fragment>
                  </RichText>
                  <RichText
                    __fromCanvasComponent={true}
                    className={'framer-1tczcl2'}
                    fonts={['Inter']}
                    layoutDependency={layoutDependency}
                    layoutId={'eCiasuf8P'}
                    style={{
                      '--framer-link-text-color': 'rgb(0, 153, 255)',
                      '--framer-link-text-decoration': 'underline'
                    }}
                    text={EDZrlkgJD}
                    verticalAlignment={'top'}
                    withExternalLayout={true}
                  >
                    <React.Fragment>
                      <motion.p
                        className={'framer-styles-preset-wu4ebp'}
                        data-styles-preset={'H1YXoF4HR'}
                      >
                        {'Stephen sures'}
                      </motion.p>
                    </React.Fragment>
                  </RichText>
                </motion.div>
              </motion.div>
            </motion.div>
            {isDisplayed() && (
              <motion.div
                className={'framer-x5bmrj'}
                data-framer-name={'line'}
                layoutDependency={layoutDependency}
                layoutId={'LwJVrxjS0'}
                style={{
                  backgroundColor:
                    'var(--token-b2b2cec5-8316-4f9c-8fd9-5fdfc3c24032, rgba(255, 255, 255, 0.1))',
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8,
                  opacity: 0.8
                }}
              />
            )}
            <ComponentViewportProvider>
              <SmartComponentScopedContainer
                className={'framer-12iylc8-container'}
                isAuthoredByUser={true}
                layoutDependency={layoutDependency}
                layoutId={'jVLrlj0ae-container'}
                nodeId={'jVLrlj0ae'}
                rendersWithMotion={true}
                scopeId={'sMosg71Yw'}
              >
                <StarRating
                  filledColor={
                    'var(--token-c858731e-e94e-456c-870f-c18178498e78, rgb(255, 215, 0))'
                  }
                  height={'100%'}
                  id={'jVLrlj0ae'}
                  layoutId={'jVLrlj0ae'}
                  rating={mp9KLmAEX}
                  starColor={
                    'var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))'
                  }
                  starSize={18}
                  textColor={
                    'var(--token-27dab558-c2be-4da2-b3df-e0c399d3b44b, rgba(255, 255, 255, 0.6))'
                  }
                  textSize={16}
                  textWeight={500}
                  width={'100%'}
                />
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
            <RichText
              __fromCanvasComponent={true}
              className={'framer-xxmpdy'}
              fonts={['Inter']}
              layoutDependency={layoutDependency}
              layoutId={'MtFREjuaq'}
              style={{
                '--framer-link-text-color': 'rgb(0, 153, 255)',
                '--framer-link-text-decoration': 'underline',
                opacity: 0.7
              }}
              text={ya3Sv_foF}
              verticalAlignment={'top'}
              withExternalLayout={true}
            >
              <React.Fragment>
                <motion.p
                  className={'framer-styles-preset-vp3sdo'}
                  data-styles-preset={'WQG2SsoyY'}
                >
                  {
                    'Start building your sites without any stress using the landerkit now, and if you have any doubts please feel free to reach out'
                  }
                </motion.p>
              </React.Fragment>
            </RichText>
            <Image
              background={{
                alt: '',
                fit: 'fill',
                loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 0),
                sizes: componentViewport?.width || '100vw',
                ...toResponsiveImage(I2vY11AUy)
              }}
              className={'framer-1ah3qff'}
              layoutDependency={layoutDependency}
              layoutId={'Vrd3mW7mF'}
              style={{
                borderBottomLeftRadius: 8,
                borderBottomRightRadius: 8,
                borderTopLeftRadius: 8,
                borderTopRightRadius: 8,
                filter: 'brightness(0.15) blur(40px)',
                opacity: 0.25,
                WebkitFilter: 'brightness(0.15) blur(40px)'
              }}
            />
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css4 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-UHQgu.framer-igv6sj, .framer-UHQgu .framer-igv6sj { display: block; }',
  '.framer-UHQgu.framer-ofwhdh { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 24px; position: relative; width: 451px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-UHQgu .framer-1dka7ig { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 3; }',
  '.framer-UHQgu .framer-8q5y6o { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }',
  '.framer-UHQgu .framer-122ls07 { aspect-ratio: 1 / 1; flex: none; height: 76px; overflow: hidden; position: relative; width: var(--framer-aspect-ratio-supported, 76px); will-change: var(--framer-will-change-override, transform); }',
  '.framer-UHQgu .framer-7civ38 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }',
  '.framer-UHQgu .framer-1p6g420, .framer-UHQgu .framer-1tczcl2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-UHQgu .framer-x5bmrj { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 3; }',
  '.framer-UHQgu .framer-12iylc8-container { flex: none; height: auto; position: relative; width: auto; }',
  '.framer-UHQgu .framer-xxmpdy { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 3; }',
  '.framer-UHQgu .framer-1ah3qff { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 1; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-UHQgu.framer-ofwhdh, .framer-UHQgu .framer-8q5y6o, .framer-UHQgu .framer-7civ38 { gap: 0px; } .framer-UHQgu.framer-ofwhdh > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-UHQgu.framer-ofwhdh > :first-child, .framer-UHQgu .framer-7civ38 > :first-child { margin-top: 0px; } .framer-UHQgu.framer-ofwhdh > :last-child, .framer-UHQgu .framer-7civ38 > :last-child { margin-bottom: 0px; } .framer-UHQgu .framer-8q5y6o > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-UHQgu .framer-8q5y6o > :first-child { margin-left: 0px; } .framer-UHQgu .framer-8q5y6o > :last-child { margin-right: 0px; } .framer-UHQgu .framer-7civ38 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } }',
  ...css3,
  ...css,
  ...css2
];
var FramersMosg71Yw = withCSS(Component, css4, 'framer-UHQgu');
var stdin_default = FramersMosg71Yw;
FramersMosg71Yw.displayName = 'review';
FramersMosg71Yw.defaultProps = {
  height: 296,
  width: 451
};
addPropertyControls(FramersMosg71Yw, {
  variant: {
    options: ['Dv19BtwkD', 'MyqbbbqiE'],
    optionTitles: ['Primary', 'No Separator Line'],
    title: 'Variant',
    type: ControlType.Enum
  },
  I2vY11AUy: {
    title: 'Image',
    type: ControlType.ResponsiveImage
  },
  P7P_MrujI: {
    defaultValue: 'Kenny Stephen',
    displayTextArea: false,
    title: 'User name',
    type: ControlType.String
  },
  EDZrlkgJD: {
    defaultValue: 'Stephen sures',
    displayTextArea: false,
    title: 'Company',
    type: ControlType.String
  },
  mp9KLmAEX: {
    defaultValue: 5,
    displayStepper: true,
    max: 5,
    min: 0,
    step: 0.1,
    title: 'Rating',
    type: ControlType.Number
  },
  ya3Sv_foF: {
    defaultValue:
      'Start building your sites without any stress using the landerkit now, and if you have any doubts please feel free to reach out',
    displayTextArea: false,
    title: 'review',
    type: ControlType.String
  }
});
addFonts(
  FramersMosg71Yw,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400'
        }
      ]
    },
    ...StarRatingFonts,
    ...getFontsFromSharedStyle(fonts3),
    ...getFontsFromSharedStyle(fonts),
    ...getFontsFromSharedStyle(fonts2)
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:review
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ReviewFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var review_default = ComponentWithRoot;
export { review_default as default };
