// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * value?: string // value
 * bottomText?: string // bottom text
}} Props

 */
import { className, css, fonts } from './chunks/chunk-NO3BJMB6.js';
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:stat-card
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/2ImLjXM0d9SUg8c168Nd/bVSOxYuK43mC6PVSlk7g/olzSS0SqM.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
import { useRef } from 'react';

// /:https://framerusercontent.com/modules/a5yurUVJFx85FFoIt2r0/uuxqHTlneWCBSxoik4cn/ILhC8lJZ4.js
import { fontStore } from 'unframer';
fontStore.loadFonts(['CUSTOM;Borgsquad Italic Italic']);
var fonts2 = [
  {
    explicitInter: true,
    fonts: [
      {
        family: 'Borgsquad Italic Italic',
        source: 'custom',
        url: 'https://framerusercontent.com/assets/gMxW4Ehphyf8G1OAYfYGykGdFBk.woff2'
      }
    ]
  }
];
var css2 = [
  '.framer-g5arJ .framer-styles-preset-py4je5:not(.rich-text-wrapper), .framer-g5arJ .framer-styles-preset-py4je5.rich-text-wrapper h3 { --framer-font-family: "Borgsquad Italic Italic", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 30px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1299px) and (min-width: 750px) { .framer-g5arJ .framer-styles-preset-py4je5:not(.rich-text-wrapper), .framer-g5arJ .framer-styles-preset-py4je5.rich-text-wrapper h3 { --framer-font-family: "Borgsquad Italic Italic", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 30px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 749px) and (min-width: 0px) { .framer-g5arJ .framer-styles-preset-py4je5:not(.rich-text-wrapper), .framer-g5arJ .framer-styles-preset-py4je5.rich-text-wrapper h3 { --framer-font-family: "Borgsquad Italic Italic", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 25px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }'
];
var className2 = 'framer-g5arJ';

// /:https://framerusercontent.com/modules/2ImLjXM0d9SUg8c168Nd/bVSOxYuK43mC6PVSlk7g/olzSS0SqM.js
var serializationHash = 'framer-NbFtm';
var variantClassNames = {
  i4jogLWTE: 'framer-v-mve1di'
};
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: 'spring'
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var getProps = ({ bottomText, height, id, value, width, ...props }) => {
  return {
    ...props,
    HFbGtqq3t: value ?? props.HFbGtqq3t ?? 'k+',
    oyel9rXPT: bottomText ?? props.oyel9rXPT ?? 'Happy users '
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className: className3,
    layoutId,
    variant,
    HFbGtqq3t,
    oyel9rXPT,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    defaultVariant: 'i4jogLWTE',
    ref: refBinding,
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [className2, className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(scopingClassNames, 'framer-mve1di', className3, classNames)}
            data-framer-name={'Primary'}
            layoutDependency={layoutDependency}
            layoutId={'i4jogLWTE'}
            ref={refBinding}
            style={{
              backgroundColor: 'var(--token-cba3b9c8-9e49-437e-aca1-1e69db3088dc, rgb(17, 17, 17))',
              borderBottomLeftRadius: 10,
              borderBottomRightRadius: 10,
              borderTopLeftRadius: 10,
              borderTopRightRadius: 10,
              boxShadow:
                '16px 24px 20px 8px rgba(0, 0, 0, 0.4), inset 0px 2px 0px 0px rgba(184, 180, 180, 0.08)',
              ...style
            }}
          >
            <motion.div
              className={'framer-hl6owf'}
              data-framer-name={'number'}
              layoutDependency={layoutDependency}
              layoutId={'lYg8bvlkp'}
            >
              <RichText
                __fromCanvasComponent={true}
                className={'framer-1jb7lob'}
                fonts={['Inter']}
                layoutDependency={layoutDependency}
                layoutId={'S3Kh5pBTI'}
                style={{
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline'
                }}
                text={HFbGtqq3t}
                verticalAlignment={'top'}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.h3
                    className={'framer-styles-preset-py4je5'}
                    data-styles-preset={'ILhC8lJZ4'}
                    style={{
                      '--framer-text-alignment': 'center'
                    }}
                  >
                    {'k+'}
                  </motion.h3>
                </React.Fragment>
              </RichText>
            </motion.div>
            <RichText
              __fromCanvasComponent={true}
              className={'framer-3j49ld'}
              fonts={['Inter']}
              layoutDependency={layoutDependency}
              layoutId={'uCu4Vt6dY'}
              style={{
                '--framer-link-text-color': 'rgb(0, 153, 255)',
                '--framer-link-text-decoration': 'underline',
                opacity: 0.5
              }}
              text={oyel9rXPT}
              verticalAlignment={'top'}
              withExternalLayout={true}
            >
              <React.Fragment>
                <motion.p
                  className={'framer-styles-preset-vp3sdo'}
                  data-styles-preset={'WQG2SsoyY'}
                  style={{
                    '--framer-text-alignment': 'center'
                  }}
                >
                  {'Happy users '}
                </motion.p>
              </React.Fragment>
            </RichText>
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css3 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-NbFtm.framer-aa13l4, .framer-NbFtm .framer-aa13l4 { display: block; }',
  '.framer-NbFtm.framer-mve1di { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 24px; position: relative; width: 138px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-NbFtm .framer-hl6owf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-NbFtm .framer-1jb7lob { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }',
  '.framer-NbFtm .framer-3j49ld { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-NbFtm.framer-mve1di, .framer-NbFtm .framer-hl6owf { gap: 0px; } .framer-NbFtm.framer-mve1di > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-NbFtm.framer-mve1di > :first-child { margin-top: 0px; } .framer-NbFtm.framer-mve1di > :last-child { margin-bottom: 0px; } .framer-NbFtm .framer-hl6owf > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-NbFtm .framer-hl6owf > :first-child { margin-left: 0px; } .framer-NbFtm .framer-hl6owf > :last-child { margin-right: 0px; } }',
  ...css2,
  ...css
];
var FramerolzSS0SqM = withCSS(Component, css3, 'framer-NbFtm');
var stdin_default = FramerolzSS0SqM;
FramerolzSS0SqM.displayName = 'stat card';
FramerolzSS0SqM.defaultProps = {
  height: 125,
  width: 138
};
addPropertyControls(FramerolzSS0SqM, {
  HFbGtqq3t: {
    defaultValue: 'k+',
    displayTextArea: false,
    title: 'value',
    type: ControlType.String
  },
  oyel9rXPT: {
    defaultValue: 'Happy users ',
    displayTextArea: false,
    title: 'bottom text',
    type: ControlType.String
  }
});
addFonts(
  FramerolzSS0SqM,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400'
        }
      ]
    },
    ...getFontsFromSharedStyle(fonts2),
    ...getFontsFromSharedStyle(fonts)
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:stat-card
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StatCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var stat_card_default = ComponentWithRoot;
export { stat_card_default as default };
