// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
'use client';

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
 * text?: string // text
}} Props

 */
import { className, css, fonts } from './chunks/chunk-NO3BJMB6.js';
import { Icon } from './chunks/chunk-BTSBQWPZ.js';
import { routes } from './chunks/chunk-23HYNGZD.js';

// virtual:tag-redirector
import { Fragment as Fragment2 } from 'react';
import { ContextProviders } from 'unframer';
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/brIhaE6oDZWlDhxCZvZo/ZxJa85MmfkQKr7n14V5U/U5vinN2SE.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext } from 'unframer';
import * as React from 'react';
import { useRef } from 'react';
var PhosphorFonts = getFonts(Icon);
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(RichText));
var enabledGestures = {
  y2xCiqjjN: {
    hover: true
  }
};
var serializationHash = 'framer-EBDBp';
var variantClassNames = {
  y2xCiqjjN: 'framer-v-4r3422'
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: 'spring'
};
var transition2 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: 'spring'
};
var animation = {
  opacity: 1,
  rotate: -36,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0
};
var animation1 = {
  opacity: 1e-3,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, text, width, ...props }) => {
  return {
    ...props,
    PiqWDVKsr: text ?? props.PiqWDVKsr ?? '(about me)',
    x4erv7m4Z: link ?? props.x4erv7m4Z
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency;
  return variants.join('-');
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className: className2,
    layoutId,
    variant,
    x4erv7m4Z,
    PiqWDVKsr,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    defaultVariant: 'y2xCiqjjN',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === 'y2xCiqjjN-hover') return true;
    return false;
  };
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link
            href={x4erv7m4Z}
            motionChild={true}
            nodeId={'y2xCiqjjN'}
            scopeId={'U5vinN2SE'}
            smoothScroll={true}
          >
            <motion.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx(scopingClassNames, 'framer-4r3422', className2, classNames)} framer-10qazvn`}
              data-framer-name={'Primary'}
              layoutDependency={layoutDependency}
              layoutId={'y2xCiqjjN'}
              ref={refBinding}
              style={{
                ...style
              }}
              {...addPropertyOverrides(
                {
                  'y2xCiqjjN-hover': {
                    'data-framer-name': void 0
                  }
                },
                baseVariant,
                gestureVariant
              )}
            >
              <motion.div
                className={'framer-1um4r9g'}
                data-framer-name={'Icon'}
                layoutDependency={layoutDependency}
                layoutId={'zho_9EFhW'}
                style={{
                  backgroundColor:
                    'var(--token-f5646347-2529-487d-8af1-d99f05c5451c, rgb(10, 10, 10))',
                  borderBottomLeftRadius: 1e3,
                  borderBottomRightRadius: 1e3,
                  borderTopLeftRadius: 1e3,
                  borderTopRightRadius: 1e3,
                  boxShadow: 'inset 0px 2px 0px 0px rgba(184, 180, 180, 0.14)',
                  rotate: -35
                }}
              >
                <ComponentViewportProvider>
                  <SmartComponentScopedContainer
                    className={'framer-1r4hh7m-container'}
                    isAuthoredByUser={true}
                    isModuleExternal={true}
                    layoutDependency={layoutDependency}
                    layoutId={'mttLS9fEM-container'}
                    nodeId={'mttLS9fEM'}
                    rendersWithMotion={true}
                    scopeId={'U5vinN2SE'}
                  >
                    <Icon
                      color={
                        'var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))'
                      }
                      height={'100%'}
                      iconSearch={'House'}
                      iconSelection={'ArrowRight'}
                      id={'mttLS9fEM'}
                      layoutId={'mttLS9fEM'}
                      mirrored={false}
                      selectByList={true}
                      style={{
                        height: '100%',
                        width: '100%'
                      }}
                      weight={'regular'}
                      width={'100%'}
                    />
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
                <ComponentViewportProvider>
                  <SmartComponentScopedContainer
                    className={'framer-13a7y3v-container'}
                    isAuthoredByUser={true}
                    isModuleExternal={true}
                    layoutDependency={layoutDependency}
                    layoutId={'yi3oBKd2z-container'}
                    nodeId={'yi3oBKd2z'}
                    rendersWithMotion={true}
                    scopeId={'U5vinN2SE'}
                  >
                    <Icon
                      color={'rgb(255, 255, 255)'}
                      height={'100%'}
                      iconSearch={'House'}
                      iconSelection={'ArrowRight'}
                      id={'yi3oBKd2z'}
                      layoutId={'yi3oBKd2z'}
                      mirrored={false}
                      selectByList={true}
                      style={{
                        height: '100%',
                        width: '100%'
                      }}
                      weight={'regular'}
                      width={'100%'}
                    />
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </motion.div>
              {isDisplayed() && (
                <RichTextWithFXWithOptimizedAppearEffect
                  __fromCanvasComponent={true}
                  __perspectiveFX={false}
                  __smartComponentFX={true}
                  __targetOpacity={1}
                  animate={animation}
                  className={'framer-fuw8zf'}
                  data-framer-appear-id={'fuw8zf'}
                  fonts={['Inter']}
                  initial={animation1}
                  layoutDependency={layoutDependency}
                  layoutId={'yn4bkAG3l'}
                  optimized={true}
                  style={{
                    '--extracted-r6o4lv':
                      'var(--token-27dab558-c2be-4da2-b3df-e0c399d3b44b, rgba(255, 255, 255, 0.6))',
                    '--framer-link-text-color': 'rgb(0, 153, 255)',
                    '--framer-link-text-decoration': 'underline',
                    rotate: -36
                  }}
                  text={PiqWDVKsr}
                  verticalAlignment={'top'}
                  withExternalLayout={true}
                >
                  <React.Fragment>
                    <motion.p
                      className={'framer-styles-preset-vp3sdo'}
                      data-styles-preset={'WQG2SsoyY'}
                      style={{
                        '--framer-text-color':
                          'var(--extracted-r6o4lv, var(--token-27dab558-c2be-4da2-b3df-e0c399d3b44b, rgba(255, 255, 255, 0.6)))'
                      }}
                    >
                      {'(about me)'}
                    </motion.p>
                  </React.Fragment>
                </RichTextWithFXWithOptimizedAppearEffect>
              )}
            </motion.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css2 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-EBDBp.framer-10qazvn, .framer-EBDBp .framer-10qazvn { display: block; }',
  '.framer-EBDBp.framer-4r3422 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 14px 0px 0px 0px; position: relative; text-decoration: none; width: min-content; }',
  '.framer-EBDBp .framer-1um4r9g { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 54px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 54px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-EBDBp .framer-1r4hh7m-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 28px); position: relative; width: 25px; }',
  '.framer-EBDBp .framer-13a7y3v-container { aspect-ratio: 1 / 1; bottom: -22px; flex: none; height: var(--framer-aspect-ratio-supported, 27px); left: -22px; position: absolute; width: 25px; z-index: 1; }',
  '.framer-EBDBp .framer-fuw8zf { bottom: -11px; flex: none; height: auto; position: absolute; right: -43px; white-space: pre; width: auto; z-index: 1; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EBDBp.framer-4r3422, .framer-EBDBp .framer-1um4r9g { gap: 0px; } .framer-EBDBp.framer-4r3422 > * { margin: 0px; margin-left: calc(24px / 2); margin-right: calc(24px / 2); } .framer-EBDBp.framer-4r3422 > :first-child { margin-left: 0px; } .framer-EBDBp.framer-4r3422 > :last-child { margin-right: 0px; } .framer-EBDBp .framer-1um4r9g > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-EBDBp .framer-1um4r9g > :first-child { margin-top: 0px; } .framer-EBDBp .framer-1um4r9g > :last-child { margin-bottom: 0px; } }',
  '.framer-EBDBp.framer-v-4r3422.hover .framer-1r4hh7m-container { height: var(--framer-aspect-ratio-supported, 27px); position: absolute; right: -22px; top: -22px; z-index: 1; }',
  '.framer-EBDBp.framer-v-4r3422.hover .framer-13a7y3v-container { bottom: unset; height: var(--framer-aspect-ratio-supported, 28px); left: unset; position: relative; }',
  ...css
];
var FramerU5vinN2SE = withCSS(Component, css2, 'framer-EBDBp');
var stdin_default = FramerU5vinN2SE;
FramerU5vinN2SE.displayName = 'tag redirector';
FramerU5vinN2SE.defaultProps = {
  height: 68,
  width: 54
};
addPropertyControls(FramerU5vinN2SE, {
  x4erv7m4Z: {
    title: 'Link',
    type: ControlType.Link
  },
  PiqWDVKsr: {
    defaultValue: '(about me)',
    description: 'keep it less than 8 letters',
    displayTextArea: false,
    title: 'text',
    type: ControlType.String
  }
});
addFonts(
  FramerU5vinN2SE,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400'
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400'
        }
      ]
    },
    ...PhosphorFonts,
    ...getFontsFromSharedStyle(fonts)
  ],
  {
    supportsExplicitInterCodegen: true
  }
);

// virtual:tag-redirector
import { WithFramerBreakpoints } from 'unframer';
import { jsx } from 'react/jsx-runtime';
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest
      })}
    </FramerContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TagRedirectorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = '', ...rest }) => {
  return (
    <FramerContextProviders
      routes={routes}
      framerSiteId={'891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </FramerContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var tag_redirector_default = ComponentWithRoot;
export { tag_redirector_default as default };
