// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 891ff71faa342f0a "Polo (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-W7F2KPGW.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-V4CXTDWK.js";
import { className, css, fonts } from "../chunks/chunk-EITFHPVU.js";
import { routes } from "../chunks/chunk-23HYNGZD.js";

// virtual:navigation/footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";
const FramerContextProviders = ContextProviders ?? (({ children }) => <>{children}</>);

// /:https://framerusercontent.com/modules/vE45o3wL4ferOMZ4FHUt/DRKnn2wnxBPwjaXfsHuX/ICELCNJiE.js
import { jsx as _jsx5, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls5,
	ComponentViewportProvider,
	ControlType as ControlType5,
	cx as cx5,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS5,
} from "unframer";
import { LayoutGroup, motion as motion5, MotionConfigContext } from "unframer";
import * as React5 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/oMiuMYAdxzz5yk7pBqrm/FToqm3dwiHuJofBRASRI/Xx_sbLkzD.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 4.5 0 L 15 16.5 L 10.5 16.5 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="16.5px" id="wBdJ15Yu6" transform="translate(4.5 3.75)" width="15px"/><path d="M 0 0 L 4.5 0 L 15 16.5 L 10.5 16.5 Z" fill="transparent" height="16.5px" id="El8uvQLqv" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(4.5 3.75)" width="15px"/><path d="M 6.176 0 L 0 6.794" fill="transparent" height="6.7940624999999955px" id="AHSzdg78i" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(4.5 13.456)" width="6.176249999999996px"/><path d="M 6.176 0 L 0 6.794" fill="transparent" height="6.794062499999999px" id="h4GjUNYzh" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(13.324 3.75)" width="6.176249999999996px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("1688045918", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-SHPPl", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css3 = [".framer-SHPPl { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon = withCSS(Component, css3, "framer-SHPPl");
Icon.displayName = "X Logo";
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/PtxaBiSAA5V6LvrpAt6G/ukoWbbXWpuIc6Sz4vRp6/UD0eTfbk_.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	useSVGTemplate as useSVGTemplate2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var Base2 = /* @__PURE__ */ forwardRef4(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG2 = motion2.create(Base2);
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG2 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG2>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg2 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13.5 0 L 4.5 0 C 2.015 0 0 2.015 0 4.5 L 0 13.5 C 0 15.985 2.015 18 4.5 18 L 13.5 18 C 15.985 18 18 15.985 18 13.5 L 18 4.5 C 18 2.015 15.985 0 13.5 0 Z M 9 12.75 C 6.929 12.75 5.25 11.071 5.25 9 C 5.25 6.929 6.929 5.25 9 5.25 C 11.071 5.25 12.75 6.929 12.75 9 C 12.75 11.071 11.071 12.75 9 12.75 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="SuXKGhab5" transform="translate(3 3)" width="18px"/><path d="M 4.5 18 C 2.015 18 0 15.985 0 13.5 L 0 4.5 C 0 2.015 2.015 0 4.5 0 L 13.5 0 C 15.985 0 18 2.015 18 4.5 L 18 13.5 C 18 15.985 15.985 18 13.5 18 Z" fill="transparent" height="18px" id="vvJ8FLDVj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 0 3.75 C 0 1.679 1.679 0 3.75 0 C 5.821 0 7.5 1.679 7.5 3.75 C 7.5 5.821 5.821 7.5 3.75 7.5 C 1.679 7.5 0 5.821 0 3.75 Z" fill="transparent" height="7.5px" id="Q3v7fjWhv" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 8.25)" width="7.5px"/><path d="M 0 1.125 C 0 0.504 0.504 0 1.125 0 C 1.746 0 2.25 0.504 2.25 1.125 C 2.25 1.746 1.746 2.25 1.125 2.25 C 0.504 2.25 0 1.746 0 1.125 Z" fill="var(--21h8s6, rgb(0, 0, 0))" height="2.25px" id="VxeO4Hprj" transform="translate(15.75 6)" width="2.25px"/></svg>';
var getProps2 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps2(props);
	const href = useSVGTemplate2("942143898", svg2);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-AT1Ex", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG2>
	);
});
var css4 = [".framer-AT1Ex { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon2 = withCSS2(Component2, css4, "framer-AT1Ex");
Icon2.displayName = "Instagram Logo";
var stdin_default3 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType2.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType2.Number,
	},
});

// /:https://framerusercontent.com/modules/RYCkzothGqoQNsbr7ktc/AFi4X0cZn1L7085iIG7P/WZdfcqIBT.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx3,
	motion as motion3,
	useSVGTemplate as useSVGTemplate3,
	withCSS as withCSS3,
} from "unframer";
import * as React3 from "react";
import { forwardRef as forwardRef6 } from "react";
var Base3 = /* @__PURE__ */ forwardRef6(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG3 = motion3.create(Base3);
var SVG3 = /* @__PURE__ */ forwardRef6((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG3 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG3>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg3 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="poRFu5DyP" transform="translate(3 3)" width="18px"/><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill="transparent" height="18px" id="Pn8o_iuqT" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 0 7.244 C 2.716 2.745 7.589 -0.003 12.844 0 C 13.349 0 13.85 0.025 14.344 0.074" fill="transparent" height="7.244064772136994px" id="MOT7Ok_Z9" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(6.656 12)" width="14.34375px"/><path d="M 14.453 0 C 11.607 3.498 7.336 5.526 2.828 5.523 C 1.879 5.523 0.932 5.434 0 5.257" fill="transparent" height="5.522817312828906px" id="uWno1dECK" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3.172 4.977)" width="14.4525px"/><path d="M 0 0 C 4.59 2.692 7.409 7.616 7.406 12.938 C 7.407 14.163 7.258 15.384 6.963 16.573" fill="transparent" height="16.573125px" id="DGpj3ZHuH" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.056 3.908)" width="7.406253430605545px"/></svg>';
var getProps3 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps3(props);
	const href = useSVGTemplate3("284710571", svg3);
	return (
		<SVG3
			{...restProps}
			className={cx3("framer-lXRR8", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG3>
	);
});
var css5 = [".framer-lXRR8 { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon3 = withCSS3(Component3, css5, "framer-lXRR8");
Icon3.displayName = "Dribbble Logo";
var stdin_default4 = Icon3;
addPropertyControls3(Icon3, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType3.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType3.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType3.Number,
	},
});

// /:https://framerusercontent.com/modules/Y0c19ostjQ6JrIrS9EpB/ZlMPPV0G0dewn2RXQ7S7/QDC8_m4BS.js
import { jsx as _jsx4 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls4,
	ControlType as ControlType4,
	cx as cx4,
	motion as motion4,
	useSVGTemplate as useSVGTemplate4,
	withCSS as withCSS4,
} from "unframer";
import * as React4 from "react";
import { forwardRef as forwardRef8 } from "react";
var Base4 = /* @__PURE__ */ forwardRef8(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG4 = motion4.create(Base4);
var SVG4 = /* @__PURE__ */ forwardRef8((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG4 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG4>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg4 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="toDPs7Y9O" transform="translate(3 3)" width="18px"/><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill="transparent" height="18px" id="nB8qhy58t" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 3.75 0 L 2.25 0 C 1.007 0 0 1.007 0 2.25 L 0 12.75" fill="transparent" height="12.75px" id="QFOnXWoYe" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(12 8.25)" width="3.75px"/><path d="M 0 0 L 6 0" fill="transparent" height="1px" id="rOK6Xhani" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(9 13.5)" width="6px"/></svg>';
var getProps4 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps4(props);
	const href = useSVGTemplate4("1426455308", svg4);
	return (
		<SVG4
			{...restProps}
			className={cx4("framer-ojcNP", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG4>
	);
});
var css6 = [".framer-ojcNP { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon4 = withCSS4(Component4, css6, "framer-ojcNP");
Icon4.displayName = "Facebook Logo";
var stdin_default5 = Icon4;
addPropertyControls4(Icon4, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType4.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType4.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType4.Number,
	},
});

// /:https://framerusercontent.com/modules/vE45o3wL4ferOMZ4FHUt/DRKnn2wnxBPwjaXfsHuX/ICELCNJiE.js
var ElementsSocialMediaFonts = getFonts(stdin_default);
var cycleOrder = ["TTt9c9jSt", "Q6QmnZD7T", "F45c4cfLk"];
var serializationHash = "framer-g56Ob";
var variantClassNames = {
	F45c4cfLk: "framer-v-12umxaq",
	Q6QmnZD7T: "framer-v-2ths7y",
	TTt9c9jSt: "framer-v-dcrxnb",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React5.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React5.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion5.create(React5.Fragment);
var humanReadableVariantMap = {
	Desktop: "TTt9c9jSt",
	Phone: "F45c4cfLk",
	Tablet: "Q6QmnZD7T",
};
var getProps5 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "TTt9c9jSt",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component5 = /* @__PURE__ */ React5.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React5.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps5(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "TTt9c9jSt",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1iqbkio = activeVariantCallback(async (...args) => {
		setVariant("F45c4cfLk");
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx5(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion5.footer
						{...restProps}
						{...gestureHandlers}
						className={cx5(
							scopingClassNames,
							"framer-dcrxnb",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"TTt9c9jSt"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								F45c4cfLk: {
									"data-framer-name": "Phone",
								},
								Q6QmnZD7T: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion5.div
							className={"framer-1ketx9k"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"y9fUjFNvV"}
						>
							<motion5.div
								className={"framer-s8zol"}
								data-framer-name={"links & others"}
								layoutDependency={layoutDependency}
								layoutId={"KpFJb91s5"}
							>
								<motion5.div
									className={"framer-1qvy87v"}
									data-framer-name={"left div"}
									layoutDependency={layoutDependency}
									layoutId={"AFFIaZaRX"}
								>
									<Link
										href={{
											hash: ":LPH2zifzT",
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"ROD1em_Xe"}
										openInNewTab={false}
										scopeId={"ICELCNJiE"}
										smoothScroll={true}
									>
										<Image
											as={"a"}
											background={{
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 423) - 200 - 351) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0,
												),
												pixelHeight: 100,
												pixelWidth: 316,
												positionX: "left",
												positionY: "center",
												src: "https://framerusercontent.com/images/duRtoIIUg5pJHSrEAoXb5RLVCc.svg",
											}}
											className={"framer-1s8ugr9 framer-b353df"}
											data-framer-name={"logo"}
											layoutDependency={layoutDependency}
											layoutId={"ROD1em_Xe"}
											{...addPropertyOverrides(
												{
													F45c4cfLk: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	64 +
																	(((componentViewport?.height || 200) -
																		112 -
																		755) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	0,
															),
															pixelHeight: 100,
															pixelWidth: 316,
															positionX: "left",
															positionY: "center",
															src: "https://framerusercontent.com/images/duRtoIIUg5pJHSrEAoXb5RLVCc.svg",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</Link>
									<motion5.nav
										className={"framer-gd6squ"}
										data-framer-name={"nav links"}
										layoutDependency={layoutDependency}
										layoutId={"xlsEpulaZ"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-7mv6oc"}
											data-framer-name={"About"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"S3RiVz7WY"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React5.Fragment>
												<motion5.p
													className={"framer-styles-preset-wu4ebp"}
													data-styles-preset={"H1YXoF4HR"}
												>
													<Link
														href={{
															hash: ":CaAED2YD5",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"S3RiVz7WY"}
														openInNewTab={false}
														preserveParams={false}
														relValues={[]}
														scopeId={"ICELCNJiE"}
														smoothScroll={true}
													>
														<motion5.a
															className={"framer-styles-preset-1bk4tro"}
															data-styles-preset={"PNICIlPkQ"}
														>
															{"Services"}
														</motion5.a>
													</Link>
												</motion5.p>
											</React5.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-11du8g5"}
											data-framer-name={"Services"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"QhgiW8UhV"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React5.Fragment>
												<motion5.p
													className={"framer-styles-preset-wu4ebp"}
													data-styles-preset={"H1YXoF4HR"}
												>
													<Link
														href={{
															hash: ":OiCXeyEiq",
															webPageId: "KZiBMHKVh",
														}}
														motionChild={true}
														nodeId={"QhgiW8UhV"}
														openInNewTab={false}
														preserveParams={false}
														relValues={[]}
														scopeId={"ICELCNJiE"}
														smoothScroll={true}
													>
														<motion5.a
															className={"framer-styles-preset-1bk4tro"}
															data-styles-preset={"PNICIlPkQ"}
														>
															{"Projects"}
														</motion5.a>
													</Link>
												</motion5.p>
											</React5.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1ew9twe"}
											data-framer-name={"Services"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Ibg4NBYhI"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React5.Fragment>
												<motion5.p
													className={"framer-styles-preset-wu4ebp"}
													data-styles-preset={"H1YXoF4HR"}
												>
													<Link
														href={{
															hash: ":ivzHkc92O",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"Ibg4NBYhI"}
														openInNewTab={false}
														preserveParams={false}
														relValues={[]}
														scopeId={"ICELCNJiE"}
														smoothScroll={true}
													>
														<motion5.a
															className={"framer-styles-preset-1bk4tro"}
															data-styles-preset={"PNICIlPkQ"}
														>
															{"Profile"}
														</motion5.a>
													</Link>
												</motion5.p>
											</React5.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1g14efx"}
											data-framer-name={"Results"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"nMkpYTFPr"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React5.Fragment>
												<motion5.p
													className={"framer-styles-preset-wu4ebp"}
													data-styles-preset={"H1YXoF4HR"}
												>
													<Link
														href={{
															hash: ":b58gIVT3I",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"nMkpYTFPr"}
														openInNewTab={false}
														preserveParams={false}
														relValues={[]}
														scopeId={"ICELCNJiE"}
														smoothScroll={true}
													>
														<motion5.a
															className={"framer-styles-preset-1bk4tro"}
															data-styles-preset={"PNICIlPkQ"}
														>
															{"Reviews"}
														</motion5.a>
													</Link>
												</motion5.p>
											</React5.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1qliv9"}
											data-framer-name={"Results"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"AlSfMncSd"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React5.Fragment>
												<motion5.p
													className={"framer-styles-preset-wu4ebp"}
													data-styles-preset={"H1YXoF4HR"}
												>
													<Link
														href={{
															hash: ":JvYUdUuKT",
															webPageId: "mMBXPq2dS",
														}}
														motionChild={true}
														nodeId={"AlSfMncSd"}
														openInNewTab={false}
														preserveParams={false}
														relValues={[]}
														scopeId={"ICELCNJiE"}
														smoothScroll={true}
													>
														<motion5.a
															className={"framer-styles-preset-1bk4tro"}
															data-styles-preset={"PNICIlPkQ"}
														>
															{"Contact"}
														</motion5.a>
													</Link>
												</motion5.p>
											</React5.Fragment>
										</RichText>
									</motion5.nav>
								</motion5.div>
								<motion5.div
									className={"framer-1q2yp1h"}
									data-framer-name={"social media row"}
									layoutDependency={layoutDependency}
									layoutId={"yeqo7n7EW"}
								>
									<ComponentViewportProvider
										height={40}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 423) - 200 - 351) / 2 +
												0 +
												0) +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												F45c4cfLk: {
													y:
														(componentViewport?.y || 0) +
														64 +
														(((componentViewport?.height || 200) - 112 - 755) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														375 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-js6fa7-container"}
											layoutDependency={layoutDependency}
											layoutId={"VUdzP1iCa-container"}
											nodeId={"VUdzP1iCa"}
											rendersWithMotion={true}
											scopeId={"ICELCNJiE"}
										>
											{_jsx5(stdin_default, {
												height: "100%",
												id: "VUdzP1iCa",
												layoutId: "VUdzP1iCa",
												v2v8tlArw: stdin_default2,
												width: "100%",
												YdTA2k7Lp: "https://x.com/home",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={40}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 423) - 200 - 351) / 2 +
												0 +
												0) +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												F45c4cfLk: {
													y:
														(componentViewport?.y || 0) +
														64 +
														(((componentViewport?.height || 200) - 112 - 755) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														375 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1r9dw75-container"}
											layoutDependency={layoutDependency}
											layoutId={"fAqdyrfGT-container"}
											nodeId={"fAqdyrfGT"}
											rendersWithMotion={true}
											scopeId={"ICELCNJiE"}
										>
											{_jsx5(stdin_default, {
												height: "100%",
												id: "fAqdyrfGT",
												layoutId: "fAqdyrfGT",
												v2v8tlArw: stdin_default3,
												width: "100%",
												YdTA2k7Lp: "https://www.instagram.com/",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={40}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 423) - 200 - 351) / 2 +
												0 +
												0) +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												F45c4cfLk: {
													y:
														(componentViewport?.y || 0) +
														64 +
														(((componentViewport?.height || 200) - 112 - 755) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														375 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1bmjsqd-container"}
											layoutDependency={layoutDependency}
											layoutId={"FSIrFsBhs-container"}
											nodeId={"FSIrFsBhs"}
											rendersWithMotion={true}
											scopeId={"ICELCNJiE"}
										>
											{_jsx5(stdin_default, {
												height: "100%",
												id: "FSIrFsBhs",
												layoutId: "FSIrFsBhs",
												v2v8tlArw: stdin_default5,
												width: "100%",
												YdTA2k7Lp: "https://www.facebook.com/",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={40}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 423) - 200 - 351) / 2 +
												0 +
												0) +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												F45c4cfLk: {
													y:
														(componentViewport?.y || 0) +
														64 +
														(((componentViewport?.height || 200) - 112 - 755) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														375 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1yi9b5k-container"}
											layoutDependency={layoutDependency}
											layoutId={"ewSYpTN0n-container"}
											nodeId={"ewSYpTN0n"}
											rendersWithMotion={true}
											scopeId={"ICELCNJiE"}
										>
											{_jsx5(stdin_default, {
												height: "100%",
												id: "ewSYpTN0n",
												layoutId: "ewSYpTN0n",
												v2v8tlArw: stdin_default4,
												width: "100%",
												YdTA2k7Lp: "https://dribbble.com/",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion5.div>
							</motion5.div>
							<motion5.div
								className={"framer-srvkd5"}
								data-framer-name={"copyrights"}
								layoutDependency={layoutDependency}
								layoutId={"FjYzkRM3Z"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-15n6vn8"}
									data-framer-name={"Made by Framebase"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"jpH3HaSy_"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React5.Fragment>
										<motion5.p
											className={"framer-styles-preset-wu4ebp"}
											data-styles-preset={"H1YXoF4HR"}
										>
											{"\xA9 2025 Polo"}
										</motion5.p>
									</React5.Fragment>
								</RichText>
								<motion5.div
									className={"framer-1cxd6k5"}
									data-framer-name={"right div"}
									layoutDependency={layoutDependency}
									layoutId={"ysSxNvGZY"}
									{...addPropertyOverrides(
										{
											F45c4cfLk: {
												"data-highlight": true,
												onTap: onTap1iqbkio,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1vrvhoo"}
										data-framer-name={"Made by Framebase"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"td9NzxKTQ"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion5.p
												className={"framer-styles-preset-wu4ebp"}
												data-styles-preset={"H1YXoF4HR"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255)))",
												}}
											>
												{"Made by "}
												<Link
													href={"https://x.com/framebase_"}
													motionChild={true}
													nodeId={"td9NzxKTQ"}
													openInNewTab={true}
													preserveParams={false}
													relValues={[]}
													scopeId={"ICELCNJiE"}
													smoothScroll={false}
												>
													<motion5.a
														className={"framer-styles-preset-1bk4tro"}
														data-styles-preset={"PNICIlPkQ"}
													>
														{"Framebase"}
													</motion5.a>
												</Link>
											</motion5.p>
										</React5.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-157nedd"}
										data-framer-name={"text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Sor3ydyMA"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion5.p
												className={"framer-styles-preset-wu4ebp"}
												data-styles-preset={"H1YXoF4HR"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255)))",
												}}
											>
												{"Built in "}
												<Link
													href={"https://framer.link/framebase"}
													motionChild={true}
													nodeId={"Sor3ydyMA"}
													openInNewTab={true}
													preserveParams={false}
													relValues={[]}
													scopeId={"ICELCNJiE"}
													smoothScroll={false}
												>
													<motion5.a
														className={"framer-styles-preset-1bk4tro"}
														data-styles-preset={"PNICIlPkQ"}
													>
														{"Framer"}
													</motion5.a>
												</Link>
											</motion5.p>
										</React5.Fragment>
									</RichText>
								</motion5.div>
							</motion5.div>
						</motion5.div>
					</motion5.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-g56Ob.framer-b353df, .framer-g56Ob .framer-b353df { display: block; }",
	".framer-g56Ob.framer-dcrxnb { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 100px 40px 100px 40px; position: relative; width: 1200px; }",
	".framer-g56Ob .framer-1ketx9k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; max-width: 1100px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-g56Ob .framer-s8zol { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-g56Ob .framer-1qvy87v { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; max-width: 1120px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-g56Ob .framer-1s8ugr9 { flex: none; height: 39px; overflow: visible; position: relative; text-decoration: none; width: 80px; }",
	".framer-g56Ob .framer-gd6squ { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-g56Ob .framer-7mv6oc, .framer-g56Ob .framer-11du8g5, .framer-g56Ob .framer-1ew9twe, .framer-g56Ob .framer-1g14efx, .framer-g56Ob .framer-1qliv9, .framer-g56Ob .framer-1vrvhoo, .framer-g56Ob .framer-157nedd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-g56Ob .framer-1q2yp1h { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-g56Ob .framer-js6fa7-container, .framer-g56Ob .framer-1r9dw75-container, .framer-g56Ob .framer-1bmjsqd-container, .framer-g56Ob .framer-1yi9b5k-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-g56Ob .framer-srvkd5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-g56Ob .framer-15n6vn8 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-g56Ob .framer-1cxd6k5 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-g56Ob.framer-v-2ths7y.framer-dcrxnb { padding: 100px 32px 100px 32px; width: 810px; }",
	".framer-g56Ob.framer-v-12umxaq.framer-dcrxnb { padding: 64px 18px 48px 18px; width: 390px; }",
	".framer-g56Ob.framer-v-12umxaq .framer-s8zol { flex-direction: column; gap: 40px; justify-content: flex-start; }",
	".framer-g56Ob.framer-v-12umxaq .framer-1qvy87v { flex: none; gap: 40px; width: 100%; }",
	".framer-g56Ob.framer-v-12umxaq .framer-gd6squ { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 24px; }",
	".framer-g56Ob.framer-v-12umxaq .framer-srvkd5 { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 32px; justify-content: flex-start; }",
	".framer-g56Ob.framer-v-12umxaq .framer-15n6vn8 { flex: none; order: 1; width: 100%; }",
	".framer-g56Ob.framer-v-12umxaq .framer-1cxd6k5 { align-content: flex-start; align-items: flex-start; cursor: pointer; flex: none; flex-direction: column; gap: 24px; order: 0; width: 100%; }",
	...css,
	...css2,
];
var FramerICELCNJiE = withCSS5(Component5, css7, "framer-g56Ob");
var stdin_default6 = FramerICELCNJiE;
FramerICELCNJiE.displayName = "Navigation / Footer";
FramerICELCNJiE.defaultProps = {
	height: 423,
	width: 1200,
};
addPropertyControls5(FramerICELCNJiE, {
	variant: {
		options: ["TTt9c9jSt", "Q6QmnZD7T", "F45c4cfLk"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType5.Enum,
	},
});
addFonts(
	FramerICELCNJiE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ElementsSocialMediaFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<FramerContextProviders
			routes={routes}
			framerSiteId={
				"891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</FramerContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<FramerContextProviders
			routes={routes}
			framerSiteId={
				"891ff71faa342f0af7ef20f0583083bbec16fee0069f0ca5cfd3ff66fcf3cd1f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</FramerContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var footer_default = ComponentWithRoot;
export { footer_default as default };
